In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [1]:
!pip install fasttext

Requirement already satisfied: fasttext in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (0.9.2)
Requirement already satisfied: pybind11>=2.2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from fasttext) (2.12.0)
Requirement already satisfied: setuptools>=0.7.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from fasttext) (68.0.0)
Requirement already satisfied: numpy in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from fasttext) (1.26.2)

In [2]:
!pip install sentence_transformers

Collecting sentence_transformers
  Downloading sentence_transformers-2.7.0-py3-none-any.whl.metadata (11 kB)
Collecting transformers<5.0.0,>=4.34.0 (from sentence_transformers)
  Downloading transformers-4.40.2-py3-none-any.whl.metadata (137 kB)
     ---------------------------------------- 0.0/138.0 kB ? eta -:--:--
     -- ------------------------------------- 10.2/138.0 kB ? eta -:--:--
     ---------- -------------------------- 41.0/138.0 kB 653.6 kB/s eta 0:00:01
     -------------------------------------- 138.0/138.0 kB 1.4 MB/s eta 0:00:00
Requirement already satisfied: tqdm in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from sentence_transformers) (4.65.0)
Requirement already satisfied: torch>=1.11.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from sentence_transformers) (2.1.1)
Requirement already satisfied: numpy in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from sentence_transformers) (1.26.2)
Requirement already satisfied: scikit-learn in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from sentence_transformers) (1.3.0)
Requirement already satisfied: scipy in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from sentence_transformers) (1.11.4)
Requirement already satisfied: huggingface-hub>=0.15.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from sentence_transformers) (0.19.4)
Requirement already satisfied: Pillow in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from sentence_transformers) (10.0.1)
Requirement already satisfied: filelock in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from huggingface-hub>=0.15.1->sentence_transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from huggingface-hub>=0.15.1->sentence_transformers) (2023.10.0)
Requirement already satisfied: requests in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from huggingface-hub>=0.15.1->sentence_transformers) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from huggingface-hub>=0.15.1->sentence_transformers) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from huggingface-hub>=0.15.1->sentence_transformers) (4.7.1)
Requirement already satisfied: packaging>=20.9 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from huggingface-hub>=0.15.1->sentence_transformers) (23.1)
Requirement already satisfied: sympy in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from torch>=1.11.0->sentence_transformers) (1.12)
Requirement already satisfied: networkx in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from torch>=1.11.0->sentence_transformers) (3.1)
Requirement already satisfied: jinja2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from torch>=1.11.0->sentence_transformers) (3.1.2)
Requirement already satisfied: colorama in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from tqdm->sentence_transformers) (0.4.6)
Requirement already satisfied: regex!=2019.12.17 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from transformers<5.0.0,>=4.34.0->sentence_transformers) (2023.10.3)
Collecting tokenizers<0.20,>=0.19 (from transformers<5.0.0,>=4.34.0->sentence_transformers)
  Downloading tokenizers-0.19.1-cp39-none-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from transformers<5.0.0,>=4.34.0->sentence_transformers) (0.4.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from scikit-learn->sentence_transformers) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from scikit-learn->sentence_transformers) (2.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from jinja2->torch>=1.11.0->sentence_transformers) (2.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests->huggingface-hub>=0.15.1->sentence_transformers) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from sympy->torch>=1.11.0->sentence_transformers) (1.3.0)
Downloading sentence_transformers-2.7.0-py3-none-any.whl (171 kB)
   ---------------------------------------- 0.0/171.5 kB ? eta -:--:--
   ------------------------------------- - 163.8/171.5 kB 10.2 MB/s eta 0:00:01
   ---------------------------------------- 171.5/171.5 kB 3.5 MB/s eta 0:00:00
Downloading transformers-4.40.2-py3-none-any.whl (9.0 MB)
   ---------------------------------------- 0.0/9.0 MB ? eta -:--:--
   - -------------------------------------- 0.2/9.0 MB 7.3 MB/s eta 0:00:02
   -- ------------------------------------- 0.6/9.0 MB 7.1 MB/s eta 0:00:02
   --- ------------------------------------ 0.9/9.0 MB 7.0 MB/s eta 0:00:02
   ----- ---------------------------------- 1.2/9.0 MB 7.2 MB/s eta 0:00:02
   ------- -------------------------------- 1.7/9.0 MB 7.6 MB/s eta 0:00:01
   --------- ------------------------------ 2.1/9.0 MB 8.0 MB/s eta 0:00:01
   ----------- ---------------------------- 2.6/9.0 MB 8.2 MB/s eta 0:00:01
   ------------- -------------------------- 3.1/9.0 MB 8.5 MB/s eta 0:00:01
   ---------------- ----------------------- 3.6/9.0 MB 8.9 MB/s eta 0:00:01
   ------------------ --------------------- 4.2/9.0 MB 9.3 MB/s eta 0:00:01
   --------------------- ------------------ 4.8/9.0 MB 9.7 MB/s eta 0:00:01
   ------------------------ --------------- 5.6/9.0 MB 10.2 MB/s eta 0:00:01
   ---------------------------- ----------- 6.4/9.0 MB 10.8 MB/s eta 0:00:01
   ------------------------------ --------- 6.9/9.0 MB 11.1 MB/s eta 0:00:01
   ------------------------------- -------- 7.0/9.0 MB 10.2 MB/s eta 0:00:01
   -------------------------------- ------- 7.4/9.0 MB 10.0 MB/s eta 0:00:01
   -------------------------------- ------- 7.4/9.0 MB 9.7 MB/s eta 0:00:01
   ---------------------------------- ----- 7.7/9.0 MB 9.3 MB/s eta 0:00:01
   ----------------------------------- ---- 8.0/9.0 MB 9.1 MB/s eta 0:00:01
   ----------------------------------- ---- 8.1/9.0 MB 8.8 MB/s eta 0:00:01
   ------------------------------------- -- 8.4/9.0 MB 8.5 MB/s eta 0:00:01
   ------------------------------------- -- 8.5/9.0 MB 8.5 MB/s eta 0:00:01
   -------------------------------------- - 8.6/9.0 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------  9.0/9.0 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------- 9.0/9.0 MB 7.7 MB/s eta 0:00:00
Downloading tokenizers-0.19.1-cp39-none-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   --- ------------------------------------ 0.2/2.2 MB 6.1 MB/s eta 0:00:01
   ------- -------------------------------- 0.4/2.2 MB 4.9 MB/s eta 0:00:01
   ----------- ---------------------------- 0.6/2.2 MB 5.5 MB/s eta 0:00:01
   -------------- ------------------------- 0.8/2.2 MB 4.8 MB/s eta 0:00:01
   ------------------- -------------------- 1.1/2.2 MB 4.8 MB/s eta 0:00:01
   ----------------------- ---------------- 1.3/2.2 MB 4.8 MB/s eta 0:00:01
   --------------------------- ------------ 1.5/2.2 MB 4.8 MB/s eta 0:00:01
   ------------------------------ --------- 1.7/2.2 MB 4.8 MB/s eta 0:00:01
   ----------------------------------- ---- 2.0/2.2 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  2.2/2.2 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 4.7 MB/s eta 0:00:00
Installing collected packages: tokenizers, transformers, sentence_transformers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.13.3
    Uninstalling tokenizers-0.13.3:
      Successfully uninstalled tokenizers-0.13.3
  Attempting uninstall: transformers
    Found existing installation: transformers 4.27.2
    Uninstalling transformers-4.27.2:
      Successfully uninstalled transformers-4.27.2
Successfully installed sentence_transformers-2.7.0 tokenizers-0.19.1 transformers-4.40.2

In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

In [2]:
import pandas as pd
import numpy as np
import json
import fasttext
import re, os, shutil, json
from os import path
from numpy.linalg import norm
import pickle

# Stop Words Processing - for data cleaning
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
sw = set(stopwords.words('english'))
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shahe\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shahe\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [3]:
#drive.mount('/content/gdrive')

defaultPath = "C:\\Users\\shahe\\FYP-PROJECT\\project\\FYP-1\\FYP\\"
Dataset_Folder = defaultPath + "Dataset2\\"
Processed_Dataset_Pickle_Path = Dataset_Folder + "processed_dataset.pkl"
Relevant_Comments_List_Pickle_Path = Dataset_Folder + "relevant_comments_list.pkl"
FastTextModelPath = defaultPath + "FastTextModelFile/cc.en.300-001.bin"

Reading Dataset Files and Merging them

In [4]:
Dataset_Files = os.listdir(Dataset_Folder)

In [5]:
DFs = []
length = 0

for file in Dataset_Files:
  if file.endswith('.csv'):
    df = pd.read_csv(Dataset_Folder + file, usecols=["author", "text"])
    DFs.append(df)
    length = length + 1

In [6]:
# Merging DataFrames

dataset_df = pd.concat(DFs)
dataset_df.shape

(4006, 2)

In [7]:
dataset_df.head(5)

            author                                               text
0         matt7054  "Hard"?, not really. It's just different, it's...
1  davidleepayne64  And when you quickly start seeing and feeling ...
2           cebow6  I quit all processed foods and only eating cle...
3   itsjillintexas  💯agreed! 👏👏👏\n\nOne of the best quotes I ever ...
0        ameventco  I want to believe this. Though everything we’v...

Dataset Preprocessing

In [8]:
# Defining Text Preprocing Function

def remove_stop_words(text):
  text_tokens = word_tokenize(text)
  tokens_without_sw = [word for word in text_tokens if not word in sw]
  return ' '.join(map(str, tokens_without_sw))


def preprocess(text):

    text = text.lower()
    text = text.replace("\\n", " ").replace("\n", " ")      # remove \n
    text = remove_stop_words(text)                          # remove stop words
    text = re.sub(r'\b\w{1,2}\b', ' ', text)                # remove words with 1 or 2 characters only
    text = re.sub(r'[^ a-zA-Z0-9]+','', text)                  # remove special characters / remove all except characters and spaces

    if text == "nan" or text == "none":
        text = " "
    text = re.sub(' +', ' ', text)

    return text.strip()

FastText - Features Generation

In [9]:
fastText_model = fasttext.load_model('cc_en_300-001-001.bin')

Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

In [10]:
def fasttext_EmbeddingsGenerator(text):
  text_embeddings = fastText_model.get_word_vector(text)
  return text_embeddings #returns one feature vector.

Sentence Transformer - Features Generation

In [11]:
def sentence_transformer_EmbeddingsGenerator(text):
  text_embeddings = model.encode(text)
  return text_embeddings

TF-IDF - Features Generation

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline

#print("no. of docs, no. of unique corpus words) : ", tfidf_features_array.shape)
#returns two dimensional feature array against the entire corpus(dataset).
def TFIDF_EmbeddingsGenerator(corpus):
  tfidf_model = TfidfVectorizer(stop_words='english')
  tfidf_model = tfidf_model.fit(corpus) #provide dataset.
  tfidf_features = tfidf_model.transform(corpus) #returns feature vectors.
  tfidf_features_array = tfidf_features.toarray() #converts to array.
  tfidf_features_list = []
  for arr in tfidf_features_array:
    tfidf_features_list.append(arr) #appending feature arrays into a list.
  return (tfidf_features_list, tfidf_model)

#generating feature array against the query.
#This function Takes in dataset's feature array and the query.
def TFIDF_QueryFeatureGeneration(tfidf_model, query):
  tfidf_features = tfidf_model.transform([query])
  tfidf_features_array = tfidf_features.toarray()
  return tfidf_features_array[0]

**Creating feature vectors of our Dataset**

In [13]:
# Looping over dataset to generate feature vectors
processed_text = []
fasttext_features = []
ST_features = []
tfidf_features = []

for index, row in dataset_df.iterrows():

  processed = preprocess(row["text"]) #sending data for cleaning.
  processed_text.append(processed) #appending in the list.

  # FastText Features Generator
  text_features = fasttext_EmbeddingsGenerator(processed) #takes in one comment at a time and returns features.
  fasttext_features.append(text_features)

  #Sentence Transformer Features Generator
  text_features2 = sentence_transformer_EmbeddingsGenerator(processed)
  ST_features.append(text_features2)

# TFIDF Features Generator
(tfidf_features, tfidf_model) = TFIDF_EmbeddingsGenerator(processed_text) #passing the corpus. The func returns the trained model and extracted features.


dataset_df["processed_text"] = processed_text
dataset_df["fasttext_features"] = fasttext_features
dataset_df["tfidf_features"] = tfidf_features
dataset_df["SentenceTransformer_features"] = ST_features

dataset_df.to_pickle(Processed_Dataset_Pickle_Path, compression='infer', protocol=5, storage_options=None) #saving features data into pickle file.

**Reading Processed Dataset**

In [14]:
dataset_df = pd.read_pickle(Processed_Dataset_Pickle_Path) #reading the file.
dataset_df.head(5)

,author,text,processed_text,fasttext_features,tfidf_features,SentenceTransformer_features
0,matt7054,"""Hard""?, not really. It's just different, it's...",hard really different choosing discipline life...,"[0.005280149, -0.00013317022, -0.0038584971, 0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.021705475, 0.021106299, -0.008713445, 0.115..."
1,davidleepayne64,And when you quickly start seeing and feeling ...,quickly start seeing feeling results inspirati...,"[-0.000931342, -0.009943034, -0.015503479, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[-0.05385817, 0.08206615, 0.033782396, -0.0033..."
2,cebow6,I quit all processed foods and only eating cle...,quit processed foods eating clean walking incl...,"[-0.0010047528, -0.004678243, -0.010162719, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[-0.013167868, 0.030945806, 0.04950701, 0.0762..."
3,itsjillintexas,💯agreed! 👏👏👏\n\nOne of the best quotes I ever ...,agreed one best quotes ever read losing weight...,"[-0.008416502, 0.0048308084, 0.0046579763, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[-0.09364073, 0.01598587, 0.04879566, 0.115423..."
0,ameventco,I want to believe this. Though everything we’v...,want believe though everything told continue t...,"[-0.0013766099, -0.000108126726, -0.0028231647...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.000119488286, 0.038193494, 0.016595503, 0.0..."

In [15]:
print("fasttext", type(dataset_df["fasttext_features"]))
print("tfidf   ", type(dataset_df["tfidf_features"]))
print("SentenceTransformer   ", type(dataset_df["SentenceTransformer_features"]))

fasttext <class 'pandas.core.series.Series'>
tfidf    <class 'pandas.core.series.Series'>
SentenceTransformer    <class 'pandas.core.series.Series'>

**Defining function to extract relevant comments w.r.t query**

In [16]:
def cosine_similarity(A, B):

  # compute cosine similarity to find the similarity between two vectors.Higher the value, higher the similarity.
  cosine = np.dot(A,B)/(norm(A)*norm(B))
  return cosine


def get_relevant_comments_indices(query, comments, top_relevant_comments):
  #finding out relevant comments by returning indexes.
#comments: list of feature vectors.
  cosine_similarities = {}
  index = 0

  for comment in comments:
    cosine = cosine_similarity(query, comment) #calculating cosine similarity between query and the feature vector in feature vector list.
    cosine_similarities[cosine] = index #making a dictionary - key-value pair, cosine is the key and index is value.
    index = index + 1

  # Sort by key
  sorted_cosine_similarities = dict(sorted(cosine_similarities.items(), reverse = True)) #returning a dict of sorted keys(highest cosine value).
  print(sorted_cosine_similarities)
  # create a list of of relevant comments indices
  relevant_indices = []
  for i in range(0, top_relevant_comments): #top_relevant_comments= count.
    key, value = list(sorted_cosine_similarities.items())[i] #accessing top values to get the index of the comment.
    relevant_indices.append(value)

  return relevant_indices

**Ask user query and find relevant comments**

In [17]:
query = input()

# query text preprocessing
processed_query = preprocess(query)

# FastText Features Generator
#query_FastText_features = fasttext_EmbeddingsGenerator(processed_query)
# TFIDF Features Generator
#query_TFIDF_features = TFIDF_QueryFeatureGeneration(tfidf_model, processed_query)
# Sentence Transformer Generator
query_ST_features = sentence_transformer_EmbeddingsGenerator(processed_query)


indices = get_relevant_comments_indices(query_ST_features, dataset_df["SentenceTransformer_features"].tolist(), 10) #giving feature vectors of query and the dataset.

print(type(query_ST_features), type(dataset_df["SentenceTransformer_features"].tolist()))
print(type(query_ST_features[0]), type(dataset_df["SentenceTransformer_features"].tolist()[0]))

# I want to adopt keto diet

 i am 22 years old what diet suits me i work out too

{0.5195413: 3869, 0.5193182: 217, 0.51783216: 2032, 0.51738393: 1128, 0.51729465: 3912, 0.51011676: 114, 0.5080644: 1804, 0.5079007: 237, 0.5067574: 121, 0.4997182: 3360, 0.49524778: 83, 0.49495405: 3756, 0.4909825: 3769, 0.4863063: 1546, 0.48620474: 131, 0.48170102: 2438, 0.47976917: 2285, 0.4778319: 138, 0.47473913: 3720, 0.4732627: 3486, 0.47179475: 3829, 0.4711719: 68, 0.46921182: 1962, 0.4682066: 2127, 0.46607316: 1098, 0.46291476: 1257, 0.46269158: 323, 0.46221963: 3546, 0.4612317: 3527, 0.45984614: 3637, 0.4594201: 3690, 0.45928517: 1720, 0.45921773: 3597, 0.45767048: 3668, 0.45762545: 2148, 0.45584002: 2886, 0.45551088: 157, 0.45524842: 1784, 0.4535135: 1245, 0.45305344: 2336, 0.45284143: 3447, 0.45243907: 212, 0.4521314: 3122, 0.4516533: 3600, 0.45090514: 1483, 0.45037436: 175, 0.450235: 23, 0.45001733: 280, 0.4499946: 1480, 0.44982624: 573, 0.44957414: 2622, 0.4491128: 1757, 0.44896036: 3748, 0.448662: 3661, 0.44781893: 3646, 0.44778103: 352, 0.44751927: 3343, 0.44576308: 1741, 0.44532228: 346, 0.44474065: 2107, 0.4437596: 1669, 0.44324628: 3363, 0.44315925: 76, 0.44254372: 516, 0.4418885: 54, 0.44169462: 89, 0.4416117: 2026, 0.44125837: 2584, 0.4409346: 975, 0.44046187: 3452, 0.4394575: 2194, 0.43921295: 436, 0.43727776: 1041, 0.4370472: 950, 0.43655533: 2414, 0.4361372: 3887, 0.4357911: 363, 0.43572283: 2030, 0.43488014: 2728, 0.43479228: 1169, 0.43477553: 1131, 0.4342658: 1659, 0.43314245: 3770, 0.43293688: 4000, 0.43282747: 1761, 0.4317046: 2842, 0.43161416: 2634, 0.43137598: 2440, 0.431028: 309, 0.43093172: 115, 0.4307217: 1679, 0.43046677: 448, 0.43033156: 99, 0.43030345: 2999, 0.43027222: 65, 0.43007037: 242, 0.4290725: 946, 0.42864683: 1472, 0.42805076: 2539, 0.42799062: 2578, 0.42779332: 1734, 0.42760438: 158, 0.4275133: 2756, 0.427322: 1022, 0.42718303: 3441, 0.4269724: 200, 0.42672023: 3364, 0.42624754: 2594, 0.42601085: 3886, 0.42539054: 3378, 0.42497307: 3629, 0.42422917: 2114, 0.42396748: 2329, 0.42322907: 3516, 0.4231122: 3651, 0.42278755: 95, 0.42250374: 3839, 0.42240068: 29, 0.42200702: 1693, 0.42181692: 507, 0.42177552: 1023, 0.42158902: 3667, 0.42115873: 106, 0.4209812: 184, 0.42088974: 562, 0.42070377: 3641, 0.4201532: 117, 0.420096: 1416, 0.41986308: 1793, 0.41982383: 908, 0.419738: 3616, 0.4192695: 1562, 0.41883048: 2806, 0.41852328: 1678, 0.4185: 1568, 0.41835466: 3789, 0.4183274: 445, 0.4178587: 2463, 0.4177735: 3832, 0.41761038: 2154, 0.41749: 3785, 0.4166875: 40, 0.41666996: 274, 0.41652235: 3570, 0.41629806: 1297, 0.41629016: 3123, 0.41614556: 2858, 0.41606933: 2581, 0.41582176: 3340, 0.41578105: 3677, 0.41577664: 3392, 0.41557115: 2069, 0.41549858: 3372, 0.41525698: 751, 0.4143915: 1255, 0.41437435: 163, 0.41436446: 1706, 0.41422325: 527, 0.41397065: 3362, 0.41393155: 3625, 0.41349503: 3687, 0.41227332: 3326, 0.41174155: 1170, 0.41124174: 3697, 0.4110444: 3624, 0.41084284: 1640, 0.41063854: 2269, 0.41063836: 1991, 0.41043103: 3472, 0.41013736: 2522, 0.40995464: 3612, 0.40975848: 2164, 0.4096042: 3449, 0.40947917: 1816, 0.40932694: 3289, 0.4093252: 3967, 0.40925822: 1122, 0.4090699: 2406, 0.40840554: 128, 0.40837765: 3276, 0.40834507: 3947, 0.40814865: 1542, 0.40810925: 189, 0.40777627: 3627, 0.40776184: 3444, 0.40710014: 3492, 0.40687558: 999, 0.4067728: 2073, 0.40663898: 3934, 0.4065448: 699, 0.40643644: 3808, 0.40629882: 3006, 0.4062372: 1500, 0.40588558: 1539, 0.40579748: 2659, 0.40568757: 2602, 0.40567905: 611, 0.40562588: 1674, 0.4054543: 3474, 0.40531147: 3216, 0.4050654: 3336, 0.40491557: 3775, 0.40476173: 3010, 0.404744: 327, 0.404666: 3348, 0.40444782: 3844, 0.40435067: 86, 0.40408957: 125, 0.40406892: 1360, 0.40357205: 3649, 0.40351713: 1099, 0.4034165: 2477, 0.40332153: 3810, 0.40318653: 3831, 0.4031142: 3973, 0.40301: 1574, 0.40272728: 3741, 0.40244344: 1032, 0.40226972: 152, 0.40222248: 3204, 0.40201616: 3755, 0.40164608: 3185, 0.40163356: 2067, 0.401192: 130, 0.40100166: 1040, 0.4004151: 1813, 0.40029252: 1974, 0.40014789: 1899, 0.4001074: 3220, 0.3999582: 126, 0.3999356: 3193, 0.39992446: 67, 0.39976048: 1687, 0.39954433: 3313, 0.39949524: 1629, 0.3993309: 1624, 0.3991373: 3691, 0.3991262: 3323, 0.39905307: 3659, 0.39902002: 3306, 0.39900756: 1234, 0.39876878: 3652, 0.3986847: 1705, 0.3986349: 1742, 0.39837468: 3354, 0.39832878: 2109, 0.39819852: 2592, 0.39818692: 1555, 0.398004: 3417, 0.39796197: 1387, 0.39794514: 3601, 0.39782965: 3703, 0.39781266: 168, 0.3976998: 1638, 0.39738804: 890, 0.3972799: 3519, 0.39697957: 1807, 0.396968: 3633, 0.3969: 2051, 0.39685708: 2527, 0.39666912: 3680, 0.3964832: 72, 0.39629444: 1495, 0.3962589: 3456, 0.39613536: 2220, 0.396106: 2534, 0.39607027: 991, 0.3959099: 1665, 0.39590135: 1418, 0.39590088: 1626, 0.39577857: 3312, 0.3957566: 3607, 0.3957063: 2495, 0.39550534: 1560, 0.39547908: 134, 0.39526105: 3811, 0.39510465: 3475, 0.39508995: 3210, 0.39500606: 3283, 0.39497936: 3754, 0.39479613: 948, 0.39459446: 2562, 0.39457828: 3222, 0.3945595: 2772, 0.39453262: 1794, 0.39450893: 1252, 0.3936782: 3613, 0.39351502: 3150, 0.3933601: 3520, 0.39322236: 534, 0.3931259: 3632, 0.3929452: 408, 0.39291906: 1473, 0.3922754: 3654, 0.39221892: 3630, 0.392134: 1449, 0.39206025: 1301, 0.39161325: 2166, 0.3912004: 3380, 0.39115644: 3300, 0.3910133: 3928, 0.39085007: 3644, 0.39071164: 30, 0.3907044: 3504, 0.39063317: 330, 0.39061707: 3622, 0.39039266: 127, 0.39005393: 1225, 0.38984376: 3676, 0.3897725: 3626, 0.38966846: 1310, 0.3896397: 3377, 0.3896131: 1812, 0.3893732: 97, 0.3893121: 3778, 0.38901216: 3828, 0.3885178: 3085, 0.3885011: 3761, 0.38825282: 1973, 0.3882441: 764, 0.3881059: 2817, 0.38798636: 2117, 0.38788342: 485, 0.387826: 3628, 0.38780847: 1258, 0.38764653: 3693, 0.387586: 1186, 0.38748893: 444, 0.3874783: 1725, 0.38745314: 3419, 0.38744318: 2256, 0.387442: 1214, 0.38736585: 3699, 0.38733503: 514, 0.3870398: 3896, 0.38688: 3870, 0.38663864: 2805, 0.3865347: 986, 0.38644505: 1285, 0.38637003: 202, 0.38605767: 1288, 0.38570553: 1217, 0.38569868: 822, 0.38528746: 315, 0.38528484: 3701, 0.3851812: 1763, 0.38517886: 807, 0.3850561: 251, 0.385026: 2985, 0.3848551: 3962, 0.3847932: 1012, 0.38478604: 3604, 0.3844676: 3955, 0.38442838: 1441, 0.3842286: 461, 0.38420284: 3774, 0.38419715: 268, 0.38414046: 2213, 0.38404286: 3529, 0.38397133: 3349, 0.38381714: 3554, 0.3838072: 372, 0.3837224: 419, 0.38327032: 605, 0.3831764: 3700, 0.3829603: 102, 0.38289064: 3499, 0.38284793: 2509, 0.38277146: 3477, 0.3825487: 388, 0.38233337: 2512, 0.38224754: 1797, 0.3820778: 3678, 0.38197654: 801, 0.38190186: 3561, 0.3814491: 1109, 0.3813157: 3009, 0.38109633: 1675, 0.381053: 1888, 0.38103825: 515, 0.38100597: 1364, 0.38097706: 3314, 0.38092893: 3631, 0.3807706: 1552, 0.38074258: 1541, 0.3803191: 1663, 0.3801822: 3591, 0.38014024: 386, 0.380057: 920, 0.38000423: 1193, 0.37997493: 1340, 0.37981054: 37, 0.37979993: 1694, 0.3797772: 3859, 0.37972847: 1139, 0.37968162: 1861, 0.37966958: 2065, 0.37965402: 340, 0.37964463: 2573, 0.3796259: 3920, 0.379332: 57, 0.37930954: 3128, 0.37927175: 1772, 0.37923563: 959, 0.37916532: 69, 0.37898952: 393, 0.37881172: 1929, 0.37878543: 932, 0.37868991: 2679, 0.3785993: 3830, 0.37837055: 1918, 0.37824976: 1867, 0.37822956: 3277, 0.37820747: 3050, 0.37803498: 3450, 0.3778737: 2428, 0.3774625: 1427, 0.37741485: 3617, 0.37713236: 3507, 0.37713224: 75, 0.37710473: 1732, 0.37703317: 3479, 0.37687257: 3764, 0.37681141: 3968, 0.37668246: 180, 0.3765885: 1758, 0.3765531: 1431, 0.376508: 3854, 0.37637156: 2489, 0.37627462: 3505, 0.37626055: 3826, 0.37621057: 3941, 0.37591615: 3982, 0.37505692: 2282, 0.37466902: 503, 0.37461546: 1486, 0.3744019: 1707, 0.37439618: 3530, 0.3741158: 1148, 0.37403834: 3112, 0.3739872: 1150, 0.37396118: 3816, 0.37378472: 120, 0.37371257: 3726, 0.37361568: 934, 0.37336335: 3704, 0.37321544: 3635, 0.37316874: 3681, 0.37315187: 3786, 0.37300885: 2604, 0.3729034: 882, 0.37288982: 354, 0.37288454: 1657, 0.37274137: 2678, 0.3725535: 483, 0.3722941: 990, 0.3720646: 1851, 0.37198347: 1453, 0.37190717: 2358, 0.37187853: 3768, 0.37178883: 124, 0.37174007: 3407, 0.37173882: 28, 0.3714727: 3404, 0.37128866: 2792, 0.37125024: 3487, 0.37121475: 497, 0.37118453: 3656, 0.37093255: 3402, 0.37085775: 3002, 0.3708: 3428, 0.37066987: 3665, 0.3705844: 925, 0.37049595: 3611, 0.3703852: 48, 0.37000516: 2551, 0.36993012: 3448, 0.3698644: 3268, 0.36985052: 2042, 0.36970955: 1601, 0.369691: 1322, 0.3695866: 1599, 0.36957425: 3606, 0.3691859: 2465, 0.3691418: 881, 0.36905932: 1877, 0.36900514: 1172, 0.3689432: 1556, 0.3688649: 103, 0.3686421: 3805, 0.36861253: 3489, 0.36853334: 3634, 0.36847678: 1643, 0.36847284: 3711, 0.36845234: 3498, 0.3683657: 2451, 0.36826572: 3273, 0.368239: 153, 0.3681896: 3296, 0.36812195: 432, 0.36805817: 2484, 0.36803693: 1685, 0.36802244: 1488, 0.36797696: 3860, 0.36791214: 3256, 0.36791098: 3609, 0.36790013: 2927, 0.3677483: 3297, 0.3676841: 3738, 0.36761853: 3473, 0.36750403: 3911, 0.36740026: 949, 0.36738682: 1630, 0.3673443: 2075, 0.3671331: 852, 0.36687505: 3515, 0.3668296: 451, 0.36681297: 512, 0.36672622: 1292, 0.366569: 2618, 0.36609954: 2930, 0.36605704: 2542, 0.36593845: 3709, 0.3658768: 1549, 0.3657592: 3946, 0.3657105: 1723, 0.3657027: 484, 0.3655246: 3599, 0.3655015: 1968, 0.36537665: 3564, 0.36527038: 2606, 0.36524096: 1145, 0.36521348: 487, 0.36509565: 250, 0.3650354: 3750, 0.36490244: 2094, 0.36485752: 3241, 0.36481607: 3270, 0.36478016: 1084, 0.36469683: 253, 0.36468968: 3689, 0.36464825: 181, 0.36463344: 1328, 0.36439067: 1134, 0.36433548: 3736, 0.36428776: 192, 0.36427727: 3497, 0.36419642: 3432, 0.36417234: 3482, 0.36409047: 1516, 0.36394775: 3586, 0.36388063: 2437, 0.3638489: 2671, 0.3637338: 1414, 0.3637029: 3783, 0.3636172: 3468, 0.36351556: 537, 0.3634724: 1224, 0.36345682: 916, 0.36343965: 234, 0.36333162: 3645, 0.3632624: 3584, 0.36318785: 1795, 0.36301875: 1476, 0.363018: 209, 0.36297378: 3248, 0.3626479: 3041, 0.36260107: 3993, 0.362539: 969, 0.3624242: 2272, 0.36229077: 1275, 0.36199227: 3126, 0.3617298: 1207, 0.3617004: 252, 0.3616615: 3127, 0.36158964: 2919, 0.36144334: 1768, 0.36143044: 1244, 0.36122933: 1086, 0.3611966: 3287, 0.36115074: 2667, 0.36091313: 1563, 0.36088324: 3932, 0.36081815: 3405, 0.36079574: 1781, 0.36038125: 2147, 0.36027706: 2393, 0.36021674: 1582, 0.36016196: 2557, 0.3600493: 2047, 0.35977522: 3781, 0.35943767: 3031, 0.35917956: 1197, 0.35917032: 3801, 0.35907927: 1551, 0.3590251: 231, 0.3590241: 3639, 0.3589994: 1071, 0.35892266: 1775, 0.35888243: 2733, 0.35879347: 422, 0.35873976: 3382, 0.35872626: 2232, 0.35866946: 2452, 0.3586524: 2890, 0.35852557: 1913, 0.35848284: 377, 0.3584774: 2133, 0.3584548: 936, 0.35843688: 2616, 0.35841388: 1294, 0.35837737: 2436, 0.35836557: 1438, 0.35834786: 3440, 0.35834044: 892, 0.35803437: 1101, 0.35798872: 110, 0.35797268: 3765, 0.357968: 3658, 0.35790616: 2766, 0.35788277: 150, 0.3578194: 563, 0.35779536: 140, 0.35768777: 849, 0.35764676: 371, 0.35749933: 164, 0.35744387: 3079, 0.3572427: 291, 0.35716388: 2074, 0.3571038: 2516, 0.35695687: 311, 0.35688514: 368, 0.35686404: 2459, 0.3567343: 3621, 0.3566972: 161, 0.35658824: 2453, 0.35657895: 3117, 0.35648018: 2058, 0.35634398: 2655, 0.35627383: 3413, 0.35624474: 548, 0.35598162: 166, 0.35590422: 405, 0.35584614: 178, 0.3556987: 2149, 0.35556722: 194, 0.35554427: 3863, 0.35554287: 1433, 0.3555147: 1661, 0.35525444: 3157, 0.35510448: 2161, 0.35479563: 767, 0.35473746: 165, 0.3546587: 1116, 0.35461336: 3653, 0.35456458: 3065, 0.35447297: 1611, 0.35446125: 3603, 0.3544147: 2261, 0.3543599: 3466, 0.3543362: 3395, 0.35431182: 51, 0.35428053: 3202, 0.35394454: 226, 0.35372132: 2877, 0.35372114: 1233, 0.35367998: 3004, 0.35356808: 3513, 0.35349458: 3311, 0.35347316: 1143, 0.35340652: 3618, 0.3533796: 1806, 0.3532274: 3598, 0.35298902: 1709, 0.35298774: 553, 0.35295612: 1749, 0.35278714: 2277, 0.3526984: 609, 0.3525715: 3695, 0.35247117: 3682, 0.35240266: 2321, 0.35233063: 3376, 0.3523207: 2396, 0.35224694: 3812, 0.35224006: 1896, 0.35191417: 3602, 0.35188204: 3164, 0.35179716: 409, 0.35177076: 1853, 0.3517679: 3384, 0.35176402: 119, 0.3517226: 510, 0.35165: 387, 0.35161492: 1597, 0.35161394: 1274, 0.3514954: 2708, 0.35140973: 1383, 0.3512636: 2938, 0.35107553: 344, 0.35102293: 423, 0.35102212: 26, 0.35098046: 1391, 0.350897: 3195, 0.35081062: 3784, 0.35078692: 945, 0.35067937: 473, 0.35062099: 3702, 0.35059947: 1439, 0.35056517: 3753, 0.35048905: 376, 0.3503745: 1605, 0.35029858: 415, 0.3502707: 1592, 0.35026255: 2951, 0.35017383: 1952, 0.350169: 3937, 0.35013252: 2057, 0.3501188: 3814, 0.3500716: 3350, 0.35002217: 3694, 0.35000026: 1324, 0.34996024: 3161, 0.34990042: 1695, 0.34986484: 3906, 0.3498506: 2171, 0.34976017: 1358, 0.34962708: 272, 0.34960932: 1514, 0.34954453: 453, 0.34950185: 828, 0.34937388: 1215, 0.34937245: 2603, 0.3491804: 1628, 0.34909967: 998, 0.34900108: 47, 0.348925: 3782, 0.34888682: 1111, 0.3488034: 1728, 0.34879667: 1511, 0.34874332: 357, 0.34863514: 1066, 0.3486019: 3588, 0.34855893: 1401, 0.34855315: 3610, 0.34843424: 1349, 0.34819287: 1037, 0.34818292: 541, 0.34813407: 872, 0.34808755: 2002, 0.34804296: 3712, 0.3478464: 3799, 0.347833: 1662, 0.34775728: 116, 0.34767595: 179, 0.34749094: 854, 0.3473609: 2943, 0.34713954: 182, 0.34707192: 826, 0.34698468: 35, 0.3469608: 3302, 0.34686595: 2175, 0.3468598: 3961, 0.34685943: 904, 0.34684843: 2541, 0.34684217: 2182, 0.34669697: 447, 0.346689: 1479, 0.3466098: 1609, 0.34611756: 2003, 0.3460577: 1800, 0.34587446: 1204, 0.34584108: 2736, 0.34582824: 3239, 0.34579304: 2315, 0.3457771: 230, 0.34572548: 2820, 0.34571344: 1776, 0.3456917: 3414, 0.3456878: 2623, 0.34567827: 678, 0.34561038: 2230, 0.34553596: 1407, 0.34551933: 1620, 0.34545642: 3047, 0.34527156: 390, 0.34523365: 2514, 0.34521103: 3596, 0.34508684: 2632, 0.3449686: 275, 0.34490344: 2944, 0.34485465: 960, 0.34468377: 2081, 0.34456125: 306, 0.3445361: 1216, 0.34452447: 1983, 0.34452227: 1501, 0.34452188: 2258, 0.3444936: 3548, 0.34432197: 255, 0.34428698: 3171, 0.34428102: 821, 0.34416512: 3550, 0.3441541: 2162, 0.3441406: 3280, 0.3439399: 1966, 0.3437793: 3562, 0.34363157: 907, 0.3435628: 2105, 0.34351343: 1316, 0.34322536: 3394, 0.34320796: 3725, 0.34307072: 3282, 0.34285504: 2535, 0.34280133: 3581, 0.34270665: 430, 0.34268516: 3899, 0.34250978: 2619, 0.34236667: 1280, 0.3423064: 3433, 0.3423016: 2505, 0.34216893: 1080, 0.3421464: 3271, 0.34188554: 2588, 0.34186557: 3796, 0.34185487: 3590, 0.34175712: 3379, 0.34175038: 3109, 0.341731: 2717, 0.34171084: 1341, 0.3416932: 3192, 0.34164834: 3523, 0.34156188: 1814, 0.34152982: 3469, 0.34148404: 1164, 0.34139156: 3197, 0.3412988: 494, 0.34123394: 2975, 0.34122202: 1350, 0.34112352: 661, 0.34111914: 3094, 0.34107584: 90, 0.34099844: 522, 0.34092984: 3046, 0.34086382: 437, 0.34084195: 3722, 0.34081286: 1034, 0.34072286: 2173, 0.3404173: 970, 0.3402522: 2501, 0.34016275: 841, 0.3401122: 518, 0.3400811: 1308, 0.34006098: 2368, 0.3400416: 359, 0.3399133: 2989, 0.33986616: 3873, 0.33983916: 2034, 0.3396418: 2153, 0.33961433: 4001, 0.33948654: 2609, 0.33945525: 1201, 0.33935404: 3007, 0.3392878: 1342, 0.33914292: 1598, 0.33911693: 3845, 0.3391124: 3666, 0.3389843: 1382, 0.33893025: 3170, 0.3388121: 859, 0.33873683: 578, 0.33845443: 992, 0.3384308: 3837, 0.3380274: 1987, 0.3378894: 2413, 0.33785886: 1593, 0.33781484: 3708, 0.33767724: 1701, 0.33766878: 3393, 0.33766258: 337, 0.33760437: 3956, 0.3375167: 1181, 0.3375124: 1043, 0.3374348: 1704, 0.337398: 3771, 0.3373921: 301, 0.33737424: 3798, 0.33731765: 1038, 0.3371893: 3732, 0.33713913: 2523, 0.33700004: 1332, 0.33697212: 3939, 0.3369176: 3001, 0.3368707: 3924, 0.3367859: 3206, 0.33676416: 1683, 0.33670655: 3933, 0.33661687: 468, 0.33660778: 2472, 0.33658224: 109, 0.33633882: 3318, 0.3363387: 3640, 0.33630416: 1000, 0.33626175: 2598, 0.33624932: 3948, 0.33621195: 2183, 0.33614856: 1266, 0.3361316: 2957, 0.33611593: 204, 0.3360451: 1894, 0.3359985: 1077, 0.33585304: 324, 0.33580852: 205, 0.3358066: 2151, 0.33579326: 112, 0.335577: 435, 0.33555236: 3999, 0.33552122: 3657, 0.33541825: 1783, 0.3352029: 3361, 0.3351699: 601, 0.33503702: 207, 0.3348997: 1067, 0.33488604: 379, 0.33458844: 4004, 0.33455482: 3970, 0.33433494: 2033, 0.33416325: 3253, 0.33413765: 971, 0.33404386: 394, 0.33402464: 1137, 0.3339846: 565, 0.3338516: 1212, 0.3338253: 3987, 0.3337574: 1907, 0.33374566: 543, 0.3336384: 1808, 0.33361712: 1591, 0.33361202: 1773, 0.33356065: 2955, 0.33351335: 3995, 0.33350888: 238, 0.33332947: 3915, 0.33324385: 1410, 0.33322603: 3551, 0.3331906: 897, 0.3331614: 2323, 0.33299467: 1025, 0.33281007: 509, 0.3327784: 1923, 0.33273143: 1698, 0.33264303: 1995, 0.33240116: 3960, 0.3323882: 3008, 0.3323776: 2124, 0.33237368: 824, 0.332332: 3904, 0.33226362: 3158, 0.33224252: 2394, 0.33210236: 3284, 0.33208168: 3686, 0.3320402: 1613, 0.33175737: 3353, 0.33172575: 2361, 0.33166134: 1690, 0.33156952: 3856, 0.3315139: 1557, 0.3314638: 3662, 0.3314132: 1478, 0.33135378: 591, 0.33119255: 2572, 0.33094788: 3026, 0.3309412: 3103, 0.33080804: 2129, 0.33076116: 3974, 0.33074045: 3169, 0.3306798: 3272, 0.33065796: 1002, 0.33063906: 267, 0.33058417: 1540, 0.3305648: 3585, 0.33049202: 2716, 0.33043566: 122, 0.33038428: 2807, 0.33038312: 3983, 0.33038086: 3189, 0.33019412: 183, 0.3301925: 621, 0.33017728: 1347, 0.33016497: 918, 0.33011797: 1319, 0.33011678: 104, 0.32998556: 3329, 0.32993585: 1241, 0.32991993: 3803, 0.32985282: 2131, 0.32983002: 674, 0.32963395: 360, 0.3296088: 985, 0.3294971: 3315, 0.32944924: 1904, 0.32910013: 2945, 0.32905996: 269, 0.32904732: 3714, 0.32897484: 2179, 0.32859898: 1396, 0.32848644: 871, 0.32842466: 1953, 0.32838827: 862, 0.32836756: 1278, 0.32832432: 3247, 0.3281594: 3322, 0.32813776: 3900, 0.32807612: 873, 0.3279652: 1334, 0.32794335: 870, 0.32787928: 80, 0.32768893: 2192, 0.32753098: 625, 0.32747796: 2626, 0.3273331: 2583, 0.3271302: 383, 0.32709616: 1397, 0.32708368: 1988, 0.3269907: 2375, 0.32693335: 3871, 0.326649: 2740, 0.32660347: 2647, 0.32655755: 2684, 0.32647958: 3927, 0.3263772: 3843, 0.32627344: 2296, 0.32626778: 2123, 0.3262291: 1535, 0.32619655: 3733, 0.3261426: 2560, 0.32597995: 3593, 0.32580623: 602, 0.3257919: 2593, 0.32574815: 2698, 0.32544297: 2245, 0.32538873: 3966, 0.32536015: 2090, 0.32535145: 923, 0.32528344: 3332, 0.3251382: 3914, 0.3248521: 1780, 0.32484004: 1564, 0.324722: 2066, 0.32459837: 517, 0.32458013: 2714, 0.32453743: 850, 0.32443774: 3638, 0.32435298: 2978, 0.32432705: 3696, 0.32425284: 1503, 0.32415083: 1430, 0.32412168: 2077, 0.3240844: 421, 0.32393306: 2395, 0.3238465: 1645, 0.32381454: 1293, 0.3237149: 614, 0.323668: 3333, 0.3236101: 606, 0.32356632: 2299, 0.32354605: 3304, 0.32348722: 20, 0.3234517: 1799, 0.32334957: 1455, 0.32323638: 3051, 0.32313502: 296, 0.3230796: 3747, 0.32301176: 2086, 0.3230097: 3018, 0.32300627: 366, 0.32297927: 513, 0.32288194: 62, 0.322796: 3249, 0.32274655: 3153, 0.322742: 1467, 0.32271442: 1729, 0.32257202: 1074, 0.32255787: 1751, 0.32253286: 3000, 0.32250175: 919, 0.3224796: 2777, 0.32242453: 10, 0.3224127: 3913, 0.32238463: 1130, 0.32234687: 3458, 0.3222157: 3698, 0.3221443: 81, 0.3220845: 402, 0.32206267: 909, 0.32203048: 2660, 0.32196084: 1999, 0.32194552: 3684, 0.3218386: 303, 0.32183456: 2658, 0.32180977: 1945, 0.32179424: 3244, 0.32169154: 2415, 0.32164437: 412, 0.32161862: 1384, 0.32150126: 3454, 0.32147813: 3500, 0.321439: 3460, 0.32140788: 96, 0.3213674: 2218, 0.3211729: 1220, 0.32111737: 362, 0.32111186: 2464, 0.3210845: 3615, 0.3210734: 3715, 0.32104582: 142, 0.32092464: 2788, 0.32081747: 1200, 0.32078168: 288, 0.32076707: 3893, 0.32071263: 956, 0.32066903: 3267, 0.32064524: 840, 0.32063505: 2498, 0.32063273: 2363, 0.32061392: 3290, 0.32059282: 734, 0.32054815: 3294, 0.32053742: 1120, 0.32048088: 85, 0.32042053: 2410, 0.3203673: 278, 0.32025316: 521, 0.3202374: 3012, 0.32011613: 3692, 0.32005876: 2200, 0.32003677: 1737, 0.3200171: 1053, 0.3199506: 2412, 0.3199372: 71, 0.3199169: 3958, 0.3198589: 3025, 0.3196069: 492, 0.31957048: 1348, 0.31955692: 1594, 0.31949216: 1980, 0.31942156: 3251, 0.3194038: 3097, 0.31928515: 1286, 0.31914145: 1505, 0.31909063: 1047, 0.31902727: 1984, 0.31

In [18]:
model_path = 'cardiffnlp/twitter-roberta-base-sentiment-latest'
from transformers import pipeline
sentiment_task = pipeline("sentiment-analysis", model=model_path, tokenizer=model_path)
sentiment_task("Covid cases are increasing fast!")

C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

[{'label': 'negative', 'score': 0.7235766649246216}]

In [19]:
arg = sentiment_task(query)

In [20]:
result = arg[0]

In [21]:
print("Label:", result['label'])

Label: neutral

In [22]:
indices

[3869, 217, 2032, 1128, 3912, 114, 1804, 237, 121, 3360]

In [23]:
relevancy_count = 1
relevant_comments_list = []
Comments_str = ""

print("Most Relevant Comments w.r.t Query\n")
for index in indices:
  comment = dataset_df.iloc[index]["text"]
  arg = sentiment_task(comment)
  result2 = arg[0]
  print(result2['label'])
  if(result2['label']== result['label'] or result['label']=='neutral'):
      print(str(relevancy_count) + " relevant comment: " + comment)
      relevancy_count = relevancy_count + 1
      relevant_comments_list.append(comment)
      Comments_str = Comments_str + comment + ". "


with open(Relevant_Comments_List_Pickle_Path, 'wb') as f:
  pickle.dump(relevant_comments_list, f)

Most Relevant Comments w.r.t Query

negative
1 relevant comment: I have 100 kg weight and my age is 15 years give me some diet plans and exersices
positive
2 relevant comment: ❤In 365 days lost 30kgs<br>❤Tshirt size XL to Medium<br>❤Feeling great.........i am living a quality life....Thank God.💥💥💥💥💥💥💥💥i am 35 yrs old but people treat me like a 25yr old🤣😅😂🤣😅😂thats the key and funpart of weight loss
neutral
3 relevant comment: I am a 68 year old female. I am 5 &#39;5 inches. I weight 144 pounds. I walk 3 miles a day. Only get sugar from fresh fruit, red meat once or twice a week. Half veggies on plate and I/4 protein, 1/4 carb. No desserts, no alcohol, no smoking, Water or coffee with just milk.  Doctors answer, well it&#39;s genetic take your meds : (    I feel like a failure. Oh I also never go out to eat. Only use olive oil on salads. Only whole wheat bread , when I splurge and eat a slice.
positive
4 relevant comment: 30 years old have a body of a 17 year old when I was in football feel and look youthful still feeling the same been on a no sugar diet over a year it really pays off.
negative
5 relevant comment: 50 years women is overweight want a perfect diet for her to help of old age women they cannot workout plzz help
neutral
6 relevant comment: A few years I could not keep up with my adult sons because I was 50 and fat. Decided it was now or never. Bought a keto book, lost 70 lbs, some weights and feel much younger and more energetic. Kayak, paddleboard and golf all the time now. Very little in the way of carbs, except carrots, berries, and peanut butter. Have kept it off for over five years and won’t go back to feeling crappy all the time
positive
7 relevant comment: I’m 52 and I’ve cut the carbs and as much sugar as possible out of my diet and other inflammatory foods .<br>Also keeping myself properly hydrated .<br>I literally feel twenty years younger.<br>The money I save on not eating junk I spend on quality , grass fed meat and line caught Salmon and organic vegetables and nuts .<br>So I’m feeling a lot better ,lost 36 pounds and eating really good food .<br>And I’m just eating less.
neutral
8 relevant comment: Thanks Dr Berg! This Was Brought Up on where does our body fat go Try using Curry powder has a lot spices black pepper cayenne pepper 🌶️ turmeric ginger cinnamon clove nutmeg Coriander Can add to salads, soups, chili 🌶️ To Your meats or drink with Apple cider vinegar, black tea, green tea Can Also make jeera water soak cumin seeds overnight add to water they all Thermogenic Winter/Spring You lose More Weight thru ThermoGenesis Wearing Black Clothing Black Shirt Long Sleeve or Sweater Can Run 🏃‍♀️ workout 🏋️‍♀️ even burn fat just listening to music 7 hrs on headphones if can handle 42 F weather
negative
9 relevant comment: Turning 30 years old and seeing how terribly people I know and care about are aging and their health problems. My diet is eat real food and limit the highly processed garbage. 130 pounds down
neutral
10 relevant comment: I was morbidly obese. Prediabetic.  Hypertension. Etc. Was not expected to live to see age 50. <br>Since changing to Whole Food Plant Based nutrition (will NOT consume processed vegan junk) I rid half my body weight of life threatening fat and now compete in ultra endurance events. I reached age 50 and more alive than I’ve ever been in my life.

In [24]:
print(relevant_comments_list)

['I have 100 kg weight and my age is 15 years give me some diet plans and exersices', '❤In 365 days lost 30kgs<br>❤Tshirt size XL to Medium<br>❤Feeling great.........i am living a quality life....Thank God.💥💥💥💥💥💥💥💥i am 35 yrs old but people treat me like a 25yr old🤣😅😂🤣😅😂thats the key and funpart of weight loss', 'I am a 68 year old female. I am 5 &#39;5 inches. I weight 144 pounds. I walk 3 miles a day. Only get sugar from fresh fruit, red meat once or twice a week. Half veggies on plate and I/4 protein, 1/4 carb. No desserts, no alcohol, no smoking, Water or coffee with just milk.  Doctors answer, well it&#39;s genetic take your meds : (    I feel like a failure. Oh I also never go out to eat. Only use olive oil on salads. Only whole wheat bread , when I splurge and eat a slice.', '30 years old have a body of a 17 year old when I was in football feel and look youthful still feeling the same been on a no sugar diet over a year it really pays off.', '50 years women is overweight want a perfect diet for her to help of old age women they cannot workout plzz help', 'A few years I could not keep up with my adult sons because I was 50 and fat. Decided it was now or never. Bought a keto book, lost 70 lbs, some weights and feel much younger and more energetic. Kayak, paddleboard and golf all the time now. Very little in the way of carbs, except carrots, berries, and peanut butter. Have kept it off for over five years and won’t go back to feeling crappy all the time', 'I’m 52 and I’ve cut the carbs and as much sugar as possible out of my diet and other inflammatory foods .<br>Also keeping myself properly hydrated .<br>I literally feel twenty years younger.<br>The money I save on not eating junk I spend on quality , grass fed meat and line caught Salmon and organic vegetables and nuts .<br>So I’m feeling a lot better ,lost 36 pounds and eating really good food .<br>And I’m just eating less.', 'Thanks Dr Berg! This Was Brought Up on where does our body fat go Try using Curry powder has a lot spices black pepper cayenne pepper 🌶️ turmeric ginger cinnamon clove nutmeg Coriander Can add to salads, soups, chili 🌶️ To Your meats or drink with Apple cider vinegar, black tea, green tea Can Also make jeera water soak cumin seeds overnight add to water they all Thermogenic Winter/Spring You lose More Weight thru ThermoGenesis Wearing Black Clothing Black Shirt Long Sleeve or Sweater Can Run 🏃\u200d♀️ workout 🏋️\u200d♀️ even burn fat just listening to music 7 hrs on headphones if can handle 42 F weather', 'Turning 30 years old and seeing how terribly people I know and care about are aging and their health problems. My diet is eat real food and limit the highly processed garbage. 130 pounds down', 'I was morbidly obese. Prediabetic.  Hypertension. Etc. Was not expected to live to see age 50. <br>Since changing to Whole Food Plant Based nutrition (will NOT consume processed vegan junk) I rid half my body weight of life threatening fat and now compete in ultra endurance events. I reached age 50 and more alive than I’ve ever been in my life.']

**Text Sumarization**

In [25]:
!pip install evaluate

Requirement already satisfied: evaluate in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (0.4.0)
Requirement already satisfied: datasets>=2.0.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (2.11.0)
Requirement already satisfied: numpy>=1.17 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (1.26.2)
Requirement already satisfied: dill in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (0.3.6)
Requirement already satisfied: pandas in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (2.1.4)
Requirement already satisfied: requests>=2.19.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (4.65.0)
Requirement already satisfied: xxhash in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (3.4.1)
Requirement already satisfied: multiprocess in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (0.70.14)
Requirement already satisfied: fsspec>=2021.05.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from fsspec[http]>=2021.05.0->evaluate) (2023.10.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (0.19.4)
Requirement already satisfied: packaging in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (23.1)
Requirement already satisfied: responses<0.19 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from evaluate) (0.18.0)
Requirement already satisfied: pyarrow>=8.0.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from datasets>=2.0.0->evaluate) (14.0.1)
Requirement already satisfied: aiohttp in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from datasets>=2.0.0->evaluate) (3.9.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from datasets>=2.0.0->evaluate) (6.0.1)
Requirement already satisfied: filelock in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (3.13.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from huggingface-hub>=0.7.0->evaluate) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests>=2.19.0->evaluate) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests>=2.19.0->evaluate) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests>=2.19.0->evaluate) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests>=2.19.0->evaluate) (2023.11.17)
Requirement already satisfied: colorama in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from tqdm>=4.62.1->evaluate) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from pandas->evaluate) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from pandas->evaluate) (2023.3)
Requirement already satisfied: attrs>=17.3.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.4)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.3)
Requirement already satisfied: six>=1.5 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.16.0)

In [37]:
import nltk
import numpy as np
import pickle
from datasets import load_dataset
from transformers import T5Tokenizer, DataCollatorForSeq2Seq
from transformers import T5ForConditionalGeneration, Seq2SeqTrainingArguments, Seq2SeqTrainer

from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM
from transformers import AutoTokenizer
from transformers import GenerationConfig

In [25]:
from transformers import AutoModelForSeq2SeqLM
from transformers import AutoTokenizer
from transformers import GenerationConfig

In [46]:
from google.colab import drive
drive.mount('/content/gdrive')

defaultPath = "/content/gdrive/MyDrive/FYP1/"
Dataset_Folder = defaultPath + "Dataset/"
Processed_Dataset_Pickle_Path = Dataset_Folder + "processed_dataset.pkl"
Relevant_Comments_List_Pickle_Path = Dataset_Folder + "relevant_comments_list.pkl"
FastTextModelPath = defaultPath + "FastTextModelFile/cc.en.300-001.bin"

ModuleNotFoundError: No module named 'google.colab'

**Read relevant_comments_list**

In [26]:
relevant_comments_list = []

with open(Relevant_Comments_List_Pickle_Path, 'rb') as f:
  relevant_comments_list = pickle.load(f)

#relevant_comments_str = relevant_comments_list[0]
relevant_comments_str = ". ".join(relevant_comments_list) #merging all comments into a single string.

In [35]:
#model_name='SyedShaheer/bart-large-cnn-samsum_tuned_V2_1'
model_name = "SyedShaheer/my_awesome_billsum_model2_v2"
model2 = AutoModelForSeq2SeqLM.from_pretrained(model_name)

config.json:   0%|          | 0.00/1.74k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/343 [00:00<?, ?B/s]

In [36]:
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

tokenizer_config.json:   0%|          | 0.00/359 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.11M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/295 [00:00<?, ?B/s]

In [32]:
dialogue = relevant_comments_str

prompt = f"""
Comment:

{dialogue}

Generate a summary?
"""

#generation_config = GenerationConfig(max_new_tokens=10, do_sample=True, temperature=0.5)

inputs = tokenizer(prompt, return_tensors='pt')


output = tokenizer.decode(
    model2.generate(
        inputs["input_ids"],
        max_new_tokens=100,
        #generation_config=generation_config,
        )[0],
    skip_special_tokens=True
)

print("-----\n")
print(f'INPUT PROMPT:\n{prompt}')

print("-----\n")
print(f'MODEL GENERATION - \n{output}\n')

-----

INPUT PROMPT:

Comment:

I have 100 kg weight and my age is 15 years give me some diet plans and exersices. ❤In 365 days lost 30kgs<br>❤Tshirt size XL to Medium<br>❤Feeling great.........i am living a quality life....Thank God.💥💥💥💥💥💥💥💥i am 35 yrs old but people treat me like a 25yr old🤣😅😂🤣😅😂thats the key and funpart of weight loss. I am a 68 year old female. I am 5 &#39;5 inches. I weight 144 pounds. I walk 3 miles a day. Only get sugar from fresh fruit, red meat once or twice a week. Half veggies on plate and I/4 protein, 1/4 carb. No desserts, no alcohol, no smoking, Water or coffee with just milk.  Doctors answer, well it&#39;s genetic take your meds : (    I feel like a failure. Oh I also never go out to eat. Only use olive oil on salads. Only whole wheat bread , when I splurge and eat a slice.. 30 years old have a body of a 17 year old when I was in football feel and look youthful still feeling the same been on a no sugar diet over a year it really pays off.. 50 years women is overweight want a perfect diet for her to help of old age women they cannot workout plzz help. A few years I could not keep up with my adult sons because I was 50 and fat. Decided it was now or never. Bought a keto book, lost 70 lbs, some weights and feel much younger and more energetic. Kayak, paddleboard and golf all the time now. Very little in the way of carbs, except carrots, berries, and peanut butter. Have kept it off for over five years and won’t go back to feeling crappy all the time. I’m 52 and I’ve cut the carbs and as much sugar as possible out of my diet and other inflammatory foods .<br>Also keeping myself properly hydrated .<br>I literally feel twenty years younger.<br>The money I save on not eating junk I spend on quality , grass fed meat and line caught Salmon and organic vegetables and nuts .<br>So I’m feeling a lot better ,lost 36 pounds and eating really good food .<br>And I’m just eating less.. Thanks Dr Berg! This Was Brought Up on where does our body fat go Try using Curry powder has a lot spices black pepper cayenne pepper 🌶️ turmeric ginger cinnamon clove nutmeg Coriander Can add to salads, soups, chili 🌶️ To Your meats or drink with Apple cider vinegar, black tea, green tea Can Also make jeera water soak cumin seeds overnight add to water they all Thermogenic Winter/Spring You lose More Weight thru ThermoGenesis Wearing Black Clothing Black Shirt Long Sleeve or Sweater Can Run 🏃‍♀️ workout 🏋️‍♀️ even burn fat just listening to music 7 hrs on headphones if can handle 42 F weather. Turning 30 years old and seeing how terribly people I know and care about are aging and their health problems. My diet is eat real food and limit the highly processed garbage. 130 pounds down. I was morbidly obese. Prediabetic.  Hypertension. Etc. Was not expected to live to see age 50. <br>Since changing to Whole Food Plant Based nutrition (will NOT consume processed vegan junk) I rid half my body weight of life threatening fat and now compete in ultra endurance events. I reached age 50 and more alive than I’ve ever been in my life.

Generate a summary?

-----

MODEL GENERATION -
In 365 days a 68-year-old female has lost 30kgs and shrunk from a size XL to a medium size size. The individual's weight loss has been achieved through a no sugar diet and a Whole Food Plant Based Nutrition diet. They have reduced their weight by 70lbs and their health has improved significantly. They are now able to compete in endurance events at the age of 50. The author recommends using Curry powder and spices to enhance their diet.

In [37]:
import numpy as np
from flask import Flask, request, render_template

app = Flask(__name__)

comments_and_answers = [
        
        ]
@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        input_value = request.form.get('input_value')

        # ----------------------------------------------------

        # TFIDF
        # query = input_value

        # # query text preprocessing
        # processed_query = preprocess(query)

        # # FastText Features Generator
        # query_FastText_features = fasttext_EmbeddingsGenerator(processed_query)
        # # TFIDF Features Generator
        # query_TFIDF_features = TFIDF_QueryFeatureGeneration(tfidf_model, processed_query)
        
        
        # indices = get_relevant_comments_indices(query_TFIDF_features, dataset_df["tfidf_features"].tolist(), 10) #giving feature vectors of query and the dataset.
        
        # print(type(query_TFIDF_features), type(dataset_df["tfidf_features"].tolist()))
        # print(type(query_TFIDF_features[0]), type(dataset_df["tfidf_features"].tolist()[0]))


        #--------------------------------------------------

        query = input_value
        
        # query text preprocessing
        processed_query = preprocess(query)
        
        # FastText Features Generator
        #query_FastText_features = fasttext_EmbeddingsGenerator(processed_query)
        # TFIDF Features Generator
        #query_TFIDF_features = TFIDF_QueryFeatureGeneration(tfidf_model, processed_query)
        # Sentence Transformer Generator
        query_ST_features = sentence_transformer_EmbeddingsGenerator(processed_query)
        
        
        indices = get_relevant_comments_indices(query_ST_features, dataset_df["SentenceTransformer_features"].tolist(), 10) #giving feature vectors of query and the dataset.
        
        print(type(query_ST_features), type(dataset_df["SentenceTransformer_features"].tolist()))
        print(type(query_ST_features[0]), type(dataset_df["SentenceTransformer_features"].tolist()[0]))
        
        # I want to adopt keto diet
        
        #------------------------------------------------------------

        arg = sentiment_task(query)
        result = arg[0]

        #------------------------------------------------------------
        
        # relevancy_count = 1
        # relevant_comments_list = []
        # Comments_str = ""
        
        # print("Most Relevant Comments w.r.t Query\n")
        # for index in indices:
        #   comment = dataset_df.iloc[index]["text"]
        #   print(str(relevancy_count) + " relevant comment: " + comment)
        #   relevancy_count = relevancy_count + 1
        #   relevant_comments_list.append(comment)
        #   Comments_str = Comments_str + comment + ". "
        
        
        # with open(Relevant_Comments_List_Pickle_Path, 'wb') as f:
        #   pickle.dump(relevant_comments_list, f)  


        #-------------------------------------------------------------

        relevancy_count = 1
        relevant_comments_list = []
        Comments_str = ""
        
        print("Most Relevant Comments w.r.t Query\n")
        for index in indices:
          comment = dataset_df.iloc[index]["text"]
          arg = sentiment_task(comment)
          result2 = arg[0]
          print(result2['label'])
          if(result2['label']== result['label'] or result['label']=='neutral'):
              print(str(relevancy_count) + " relevant comment: " + comment)
              relevancy_count = relevancy_count + 1
              relevant_comments_list.append(comment)
              Comments_str = Comments_str + comment + ". "
        
        
        with open(Relevant_Comments_List_Pickle_Path, 'wb') as f:
          pickle.dump(relevant_comments_list, f)

        #---------------------------------------------------------

        relevant_comments_list = []

        with open(Relevant_Comments_List_Pickle_Path, 'rb') as f:
          relevant_comments_list = pickle.load(f)

        #relevant_comments_str = relevant_comments_list[0]
        relevant_comments_str = ". ".join(relevant_comments_list) #merging all comments into a single string.
        #--------------------------------------------

        # model_name='SyedShaheer/distilbart-cnn-12-6_TUNED'
        # model2 = AutoModelForSeq2SeqLM.from_pretrained(model_name)

        # #----------------------------------------------

        # tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

        #-----------------------------------------------

        dialogue = relevant_comments_str
        
        prompt = f"""
        Comment:
        
        {dialogue}
        
        Generate a summary?
        """
        
        #generation_config = GenerationConfig(max_new_tokens=10, do_sample=True, temperature=0.5)
        
        inputs = tokenizer(prompt, return_tensors='pt')
        
        
        output = tokenizer.decode(
            model2.generate(
                inputs["input_ids"],
                max_new_tokens=100,
                #generation_config=generation_config,
                )[0],
            skip_special_tokens=True
        )
        
        print("-----\n")
        print(f'INPUT PROMPT:\n{prompt}')
        
        print("-----\n")
        print(f'MODEL GENERATION - \n{output}\n')

        
        pred =  query
        ans= output   

        new_comment = {"question": query , "answer": output}
        
        comments_and_answers.append(new_comment)
        # Perform prediction using input_value here


        
        prediction = input_value  # Dummy prediction, replace with actual prediction
        return render_template('index.html', prediction=pred, answer=ans, comments_and_answers=comments_and_answers )
    return render_template('index.html', prediction=None)

if __name__ == "__main__":
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [15/May/2024 14:30:13] "GET / HTTP/1.1" 200 -

{0.8218853: 602, 0.7877576: 3578, 0.7701569: 3938, 0.7665896: 3927, 0.76121557: 3920, 0.756304: 312, 0.7484742: 3865, 0.7416311: 3760, 0.74041426: 509, 0.73436314: 147, 0.72426265: 3821, 0.7202334: 3880, 0.71678454: 3840, 0.7154149: 3751, 0.7130557: 451, 0.7119352: 3867, 0.7116881: 3971, 0.7089199: 3855, 0.7063969: 3733, 0.70178473: 3721, 0.69599104: 3595, 0.6929783: 3888, 0.69218063: 3566, 0.68946606: 3833, 0.6891098: 3613, 0.68856454: 3723, 0.6883923: 3508, 0.6867504: 238, 0.6859802: 3684, 0.68466604: 3859, 0.68287444: 3765, 0.6822119: 3914, 0.68060845: 3755, 0.67901784: 3795, 0.6769308: 1004, 0.67681897: 181, 0.6767155: 1074, 0.6760112: 3714, 0.6748235: 3594, 0.673703: 3842, 0.67347336: 3899, 0.6732573: 3606, 0.6719056: 4001, 0.6712522: 3740, 0.67045116: 3600, 0.66758746: 430, 0.6668779: 516, 0.6666468: 3592, 0.6665815: 3616, 0.6663107: 564, 0.6658935: 3788, 0.6653675: 3587, 0.6634614: 2937, 0.6630789: 1269, 0.66152877: 3802, 0.66137415: 1675, 0.6612989: 3929, 0.66087115: 1030, 0.660658: 3586, 0.6597114: 3823, 0.65778786: 176, 0.6569177: 1139, 0.65674376: 3768, 0.6563864: 3878, 0.65518457: 3564, 0.65505415: 3608, 0.654318: 3580, 0.65261775: 1617, 0.6521812: 1044, 0.65054715: 3565, 0.64999574: 3558, 0.64904416: 3568, 0.64731944: 3591, 0.64685965: 180, 0.6461843: 122, 0.6456859: 573, 0.6455238: 1691, 0.6454115: 3889, 0.6429909: 3816, 0.64165235: 3948, 0.6404003: 90, 0.63947034: 1665, 0.638872: 2346, 0.6386527: 3894, 0.6384378: 3810, 0.6375218: 2059, 0.6365509: 3839, 0.63647217: 3997, 0.63593954: 3805, 0.63589525: 934, 0.6352702: 3905, 0.6345295: 3737, 0.6339825: 388, 0.63383913: 3240, 0.63365936: 3874, 0.63325876: 606, 0.6323458: 510, 0.6319713: 3567, 0.6318953: 2735, 0.6297376: 576, 0.6292739: 3637, 0.629127: 3909, 0.6290856: 3979, 0.62872237: 3746, 0.6278323: 3589, 0.6274047: 3827, 0.6273625: 3710, 0.62638295: 3731, 0.62299913: 3897, 0.6224357: 3722, 0.6209505: 3704, 0.62084824: 3563, 0.62015355: 1728, 0.61931235: 3851, 0.6193026: 3782, 0.6192871: 127, 0.6191098: 3933, 0.6177115: 3783, 0.6172901: 3829, 0.6171901: 1705, 0.616667: 3744, 0.6164528: 1738, 0.616309: 3605, 0.6162822: 182, 0.6161372: 3741, 0.61611587: 1609, 0.61597717: 1327, 0.61513233: 3890, 0.61431396: 3856, 0.6122858: 3974, 0.6113527: 3694, 0.6109516: 3787, 0.6108352: 3148, 0.6107192: 565, 0.6105798: 1981, 0.6086811: 3801, 0.6053382: 357, 0.6031587: 232, 0.6029874: 3753, 0.60278726: 3057, 0.602336: 3562, 0.6012922: 3607, 0.60116076: 561, 0.6007747: 3055, 0.6007658: 640, 0.60010934: 111, 0.599825: 47, 0.5988888: 3603, 0.5983716: 1292, 0.59658986: 81, 0.5947746: 3934, 0.59463245: 3747, 0.5943755: 3601, 0.59437007: 3736, 0.5938833: 3609, 0.59377104: 3241, 0.59321976: 2117, 0.5931121: 3156, 0.59179866: 1605, 0.5916077: 734, 0.59132946: 3612, 0.59060943: 3772, 0.59022087: 2943, 0.58969265: 3582, 0.5893664: 1736, 0.5892443: 3750, 0.5885347: 3596, 0.58778334: 563, 0.58602387: 1291, 0.5855784: 3602, 0.5855438: 1433, 0.5852047: 3797, 0.5847373: 3947, 0.5837914: 1662, 0.5834387: 998, 0.5832425: 175, 0.58320814: 3796, 0.58299184: 2633, 0.5822145: 1821, 0.58116436: 2788, 0.58115244: 3825, 0.5806671: 1054, 0.58054477: 1038, 0.5801158: 140, 0.57859194: 2363, 0.5782276: 3570, 0.57774675: 3980, 0.57684636: 3864, 0.57615685: 1146, 0.57604206: 1234, 0.5757188: 3799, 0.57552755: 3946, 0.5750332: 999, 0.57424426: 3943, 0.5738685: 2745, 0.57301307: 89, 0.57225096: 1773, 0.57158864: 3752, 0.5714403: 3610, 0.570506: 3835, 0.57033587: 3579, 0.56996524: 3780, 0.5698855: 3236, 0.5696637: 3604, 0.5691787: 1120, 0.5685209: 3794, 0.56816846: 1516, 0.56781125: 3965, 0.56741166: 582, 0.5674057: 674, 0.5663695: 2460, 0.565866: 291, 0.5654241: 236, 0.5648612: 1629, 0.5644521: 3719, 0.5643867: 3967, 0.5629624: 2440, 0.5625997: 3989, 0.56258476: 3673, 0.5617795: 1751, 0.5607874: 359, 0.560401: 1064, 0.56019384: 1549, 0.5588784: 3970, 0.55748695: 3987, 0.5569676: 482, 0.5564474: 110, 0.55585235: 3706, 0.554946: 99, 0.55378896: 443, 0.55354154: 113, 0.55333304: 3806, 0.55286133: 1894, 0.55275756: 921, 0.55221236: 3766, 0.55216706: 1661, 0.55211985: 3585, 0.55182385: 652, 0.5515653: 1807, 0.55147094: 290, 0.55123776: 59, 0.54926777: 1068, 0.54904747: 1066, 0.54816246: 3777, 0.54805255: 1638, 0.54773396: 3950, 0.5473159: 51, 0.54631263: 374, 0.54610455: 1780, 0.5455507: 797, 0.5452388: 953, 0.5451627: 503, 0.5449225: 3922, 0.5446855: 984, 0.54441965: 3973, 0.54429626: 3670, 0.5438024: 3924, 0.54323155: 136, 0.5426315: 1574, 0.54260635: 2487, 0.5424: 2890, 0.5418229: 2476, 0.5413767: 3647, 0.5396229: 3588, 0.5392754: 164, 0.53918207: 579, 0.53840613: 300, 0.5383: 3276, 0.53762263: 1112, 0.5374039: 530, 0.53708076: 521, 0.5368571: 2581, 0.53614163: 183, 0.53590804: 3972, 0.5354996: 1748, 0.53548676: 3743, 0.53482926: 3597, 0.5340737: 1703, 0.5340253: 3808, 0.53395015: 1062, 0.5333029: 321, 0.5330825: 1599, 0.53216726: 3904, 0.5319125: 1348, 0.5306944: 94, 0.53060937: 1795, 0.53028554: 3955, 0.529378: 3820, 0.5292563: 70, 0.5284358: 1589, 0.5280574: 817, 0.5271415: 3707, 0.52655774: 3916, 0.5264873: 1496, 0.5260613: 2695, 0.5258682: 1674, 0.524723: 1745, 0.52443004: 3903, 0.5236727: 3901, 0.52362305: 840, 0.52315146: 1086, 0.5231065: 170, 0.5225826: 1820, 0.521539: 789, 0.52067524: 969, 0.5199802: 3819, 0.5197816: 3778, 0.5192641: 3807, 0.5187851: 124, 0.5185598: 2176, 0.5182867: 1827, 0.5182743: 3991, 0.51819116: 2669, 0.51768625: 3793, 0.5175139: 3957, 0.5170903: 641, 0.5169313: 1427, 0.5167382: 3599, 0.5158747: 303, 0.5157582: 1523, 0.51525104: 301, 0.51441664: 3734, 0.5143521: 2679, 0.5141911: 2626, 0.5141472: 177, 0.51365054: 2613, 0.5134854: 3343, 0.5127917: 945, 0.5127841: 3357, 0.51198816: 78, 0.5119634: 2632, 0.511723: 1673, 0.5111449: 1597, 0.51083827: 1294, 0.51046264: 3559, 0.51040083: 2647, 0.5099208: 3630, 0.50852364: 119, 0.50673974: 504, 0.50557995: 396, 0.50518805: 1097, 0.5051206: 1742, 0.5023304: 3771, 0.5021493: 3742, 0.50207895: 1153, 0.4999889: 158, 0.4999405: 126, 0.4994386: 3666, 0.49833328: 3622, 0.4982863: 2381, 0.49813253: 3668, 0.49743837: 2925, 0.49654725: 826, 0.4963796: 3745, 0.49610788: 1404, 0.49603745: 1449, 0.49551314: 960, 0.4947537: 3395, 0.4945828: 2509, 0.49405417: 963, 0.49396777: 1022, 0.49382666: 3786, 0.493656: 18, 0.4936472: 3784, 0.4936427: 982, 0.49331006: 2344, 0.49285644: 3646, 0.49244022: 1222, 0.49243194: 3641, 0.4922748: 2055, 0.49200797: 2285, 0.4913747: 2378, 0.49131286: 3407, 0.49123675: 1952, 0.49102372: 3691, 0.49080822: 3883, 0.4899346: 3928, 0.48986384: 207, 0.48982468: 2541, 0.48963612: 2896, 0.48881143: 3954, 0.48874882: 1630, 0.48861104: 935, 0.4884958: 3658, 0.48846263: 2148, 0.4872137: 1797, 0.48704672: 3652, 0.48646832: 2103, 0.48634046: 2512, 0.48609698: 2648, 0.48565343: 1023, 0.48550212: 2366, 0.48546126: 2034, 0.4852457: 1596, 0.48520407: 1418, 0.48383468: 1933, 0.48380488: 1089, 0.4837808: 3687, 0.48308372: 3034, 0.48294038: 3966, 0.48291928: 3247, 0.48284388: 2413, 0.48283637: 1323, 0.4827801: 3590, 0.48230213: 942, 0.48221782: 1531, 0.48221195: 1081, 0.481801: 62, 0.48092484: 502, 0.48012945: 390, 0.4797948: 348, 0.4797905: 1410, 0.47957438: 562, 0.47915325: 854, 0.4785335: 1395, 0.47849232: 1633, 0.47832465: 843, 0.4776408: 1358, 0.47700724: 2404, 0.47699136: 2599, 0.47676077: 3384, 0.4765586: 102, 0.47652346: 63, 0.4764127: 1328, 0.47619703: 3758, 0.47543716: 1542, 0.47543216: 3986, 0.47535765: 330, 0.47530505: 131, 0.47487304: 890, 0.47458115: 1473, 0.47456843: 3648, 0.47433418: 1697, 0.47426116: 1982, 0.47424054: 1592, 0.47399208: 1626, 0.47318494: 1413, 0.47285575: 3699, 0.47276455: 584, 0.47237432: 2531, 0.47224832: 3534, 0.47201422: 376, 0.47148377: 2553, 0.4712851: 2474, 0.47123748: 501, 0.47116274: 1472, 0.4710842: 2610, 0.47095847: 2469, 0.47060803: 1047, 0.47025004: 1396, 0.46995434: 3945, 0.46969366: 1077, 0.469536: 3624, 0.46932122: 1704, 0.46899864: 76, 0.46806008: 852, 0.46780193: 1278, 0.46767482: 1319, 0.46757227: 3527, 0.46657288: 2692, 0.46625373: 448, 0.46619934: 3906, 0.46594524: 3804, 0.46590492: 1426, 0.46540526: 439, 0.46482554: 1114, 0.4646421: 2728, 0.46436405: 1443, 0.46334505: 3447, 0.46322343: 3451, 0.46296516: 1658, 0.46277437: 1587, 0.46244216: 626, 0.46175435: 1340, 0.46137068: 703, 0.46122268: 1127, 0.46092796: 1611, 0.4603218: 1514, 0.45939302: 3996, 0.45927757: 515, 0.4591912: 3759, 0.4588846: 3678, 0.45803887: 3886, 0.45793778: 3656, 0.45748106: 3214, 0.45719212: 1466, 0.45683923: 383, 0.4568215: 3448, 0.4562106: 970, 0.4558541: 1992, 0.45577025: 2436, 0.4556253: 1259, 0.45559195: 2924, 0.45554084: 2535, 0.45553482: 445, 0.45529148: 3964, 0.45442882: 3127, 0.4538566: 3881, 0.45346516: 3222, 0.45338732: 2453, 0.45313057: 1645, 0.45291698: 605, 0.45281538: 1461, 0.45259136: 1310, 0.45241782: 92, 0.45200744: 1553, 0.4519996: 3280, 0.45199552: 2604, 0.4519617: 1816, 0.4516388: 1295, 0.45134574: 3252, 0.45120355: 2533, 0.4505245: 2434, 0.4503366: 3628, 0.4502644: 543, 0.45006013: 1707, 0.4499068: 3627, 0.4496873: 471, 0.44938916: 1569, 0.44932517: 1732, 0.44917938: 479, 0.44914684: 1041, 0.44914138: 3992, 0.4488078: 1441, 0.44879797: 3891, 0.4487014: 53, 0.4486571: 598, 0.44860464: 2417, 0.44850454: 583, 0.448471: 3918, 0.44830027: 1664, 0.44829404: 2465, 0.44811076: 2405, 0.4478441: 3048, 0.4474691: 1544, 0.44735903: 3626, 0.44595942: 3171, 0.44588298: 1593, 0.44584703: 1815, 0.44567835: 2602, 0.44564658: 368, 0.44564548: 3679, 0.44555026: 165, 0.44528985: 2354, 0.44528013: 393, 0.4452021: 3659, 0.44507805: 1293, 0.44504982: 932, 0.4449718: 2594, 0.44479525: 346, 0.44460106: 1061, 0.4440516: 1367, 0.44396588: 3701, 0.44351012: 184, 0.44311225: 2699, 0.44310787: 96, 0.44278902: 3677, 0.44257647: 3657, 0.4425467: 256, 0.44246277: 2298, 0.4423234: 95, 0.44113484: 1643, 0.44112903: 3556, 0.44064718: 22, 0.44047892: 2557, 0.44036478: 3369, 0.44025075: 2062, 0.43997937: 1154, 0.43993047: 171, 0.43985954: 3717, 0.43973374: 2042, 0.43968672: 3639, 0.43965745: 123, 0.43961546: 2704, 0.4394646: 1948, 0.43890548: 1243, 0.43809694: 447, 0.43796572: 3693, 0.43777436: 2009, 0.43759865: 3838, 0.43736258: 2033, 0.43708184: 2542, 0.4368956: 1316, 0.43620443: 3861, 0.43616444: 2727, 0.43609232: 1059, 0.4360405: 1303, 0.43582234: 157, 0.43525264: 3949, 0.43521947: 3690, 0.4351566: 3697, 0.43501037: 1025, 0.43464625: 4000, 0.43461004: 1106, 0.43447092: 3939, 0.43446493: 1709, 0.4335363: 1552, 0.4330063: 986, 0.43237683: 3896, 0.43234202: 1504, 0.4323079: 2416, 0.43201834: 918, 0.4319124: 244, 0.43174928: 3961, 0.43163127: 537, 0.4315674: 2634, 0.43154785: 1297, 0.43154776: 1562, 0.4309387: 1475, 0.43080187: 3811, 0.43076628: 3870, 0.43070206: 250, 0.4302296: 73, 0.43011314: 3298, 0.429484: 911, 0.42945766: 1669, 0.42943457: 1447, 0.42915604: 917, 0.4291034: 3611, 0.42891896: 3832, 0.4284798: 265, 0.42830968: 3761, 0.42793933: 2988, 0.42769653: 1794, 0.42741817: 2792, 0.42712137: 951, 0.42680353: 2551, 0.42651418: 2740, 0.42602348: 255, 0.42579103: 1722, 0.42577958: 2570, 0.42565665: 114, 0.42524248: 1131, 0.4250473: 3709, 0.42494237: 2358, 0.42483878: 3936, 0.42481193: 3831, 0.4247122: 212, 0.42451373: 83, 0.42428228: 2149, 0.42382628: 3561, 0.42374274: 1532, 0.42365944: 172, 0.4235748: 54, 0.42353624: 3726, 0.42328385: 512, 0.42326826: 1478, 0.42303255: 2592, 0.422908: 389, 0.422651: 3122, 0.4224436: 3892, 0.4223221: 1454, 0.42199948: 3661, 0.4218998: 2717, 0.42174077: 3798, 0.42162946: 1685, 0.42147687: 3634, 0.42137426: 3844, 0.42071134: 2232, 0.420709: 134, 0.42069578: 3756, 0.4205273: 1476, 0.42046925: 2985, 0.42043918: 3662, 0.42041814: 3007, 0.42038056: 1341, 0.42015177: 3103, 0.42013785: 1027, 0.42007008: 3050, 0.4199692: 2026, 0.4198176: 468, 0.41981: 791, 0.41963926: 3479, 0.41957235: 3952, 0.41946658: 1071, 0.41936022: 2028, 0.41900608: 2746, 0.41863406: 3995, 0.4185644: 3781, 0.4185453: 201, 0.41837773: 2464, 0.4183246: 2336, 0.4182903: 1588, 0.4181532: 2069, 0.41806847: 3688, 0.41788158: 179, 0.41787237: 168, 0.4178066: 2684, 0.4175445: 2820, 0.41749358: 3725, 0.41737932: 1679, 0.41734424: 3660, 0.41732195: 2573, 0.41712302: 907, 0.4170663: 514, 0.41703472: 1729, 0.4170308: 3631, 0.41637364: 231, 0.41623515: 1245, 0.4161175: 882, 0.41593596: 2006, 0.4153542: 1244, 0.41522875: 1252, 0.41494972: 2393, 0.41476116: 1509, 0.41466832: 1676, 0.41459823: 408, 0.41458508: 1224, 0.4143991: 1557, 0.41439772: 1204, 0.41396677: 1907, 0.41393653: 2138, 0.41378146: 1690, 0.41374034: 1749, 0.41361555: 268, 0.41319558: 1495, 0.41314653: 327, 0.41312033: 3686, 0.41308254: 1320, 0.41305226: 1201, 0.4130131: 3803, 0.41292968: 1148, 0.41280836: 801, 0.41278198: 3653, 0.41236895: 3703, 0.41205376: 1735, 0.4120061: 1501, 0.41156524: 1693, 0.4115187: 2258, 0.41151613: 3932, 0.41150072: 2439, 0.41133305: 3960, 0.41128415: 3633, 0.41118723: 3161, 0.41116017: 1804, 0.41111508: 80, 0.41101855: 138, 0.41063294: 2164, 0.41035613: 3621, 0.41030613: 3077, 0.41004467: 117, 0.4098807: 3640, 0.40947223: 194, 0.4093455: 534, 0.40928036: 1784, 0.40884835: 3702, 0.40882832: 3735, 0.4087324: 2989, 0.40854248: 3093, 0.40836266: 3126, 0.40829414: 3990, 0.40827912: 3665, 0.4075411: 956, 0.4073937: 948, 0.40729403: 3625, 0.40719923: 3216, 0.40677294: 1606, 0.4064517: 3871, 0.40623784: 192, 0.40588734: 1335, 0.40578318: 2667, 0.40573838: 315, 0.40517834: 3380, 0.4045956: 914, 0.4044174: 2011, 0.40433055: 3792, 0.40430093: 2591, 0.40420017: 1202, 0.4036315: 980, 0.403338: 3316, 0.40309912: 2668, 0.40309337: 1255, 0.40289283: 3332, 0.402761: 2067, 0.4027499: 3834, 0.4026812: 360, 0.40218282: 2049, 0.4019449: 3250, 0.4012962: 1579, 0.40123472: 2058, 0.40101308: 829, 0.40091255: 2823, 0.40085953: 2584, 0.4007917: 48, 0.4007804: 1116, 0.40060169: 1439, 0.40013173: 994, 0.40000707: 1551, 0.399997: 1759, 0.39998215: 862, 0.39939007: 146, 0.3993157: 3956, 0.3992169: 3649, 0.3990019: 915, 0.39860147: 226, 0.39846265: 2446, 0.39844537: 625, 0.39818615: 3651, 0.3981346: 1724, 0.39779097: 1919, 0.39775434: 2659, 0.39769772: 2714, 0.39760298: 3654, 0.39755666: 3817, 0.3972155: 1468, 0.3971333: 2738, 0.39713323: 437, 0.39713016: 2569, 0.39712018: 166, 0.39694026: 957, 0.39692324: 873, 0.39659768: 3715, 0.39656138: 288, 0.39636225: 3937, 0.3962803: 3872, 0.3962437: 3051, 0.39622876: 2583, 0.3962139: 56, 0.39587024: 1970, 0.39581794: 959, 0.39572665: 1387, 0.39571014: 68, 0.39567262: 895, 0.3956501: 3129, 0.39505896: 3732, 0.39487022: 3581, 0.39481094: 822, 0.3945883: 1511, 0.3945548: 3728, 0.3945112: 3907, 0.3941466: 190, 0.3941243: 1575, 0.39411983: 1008, 0.3940153: 1058, 0.39393052: 580, 0.3937723: 3843, 0.39375365: 2623, 0.3936272: 2919, 0.39350557: 1046, 0.3933059: 2698, 0.39329484: 1683, 0.3931599: 1710, 0.3929971: 452, 0.3928209: 93, 0.39276817: 881, 0.39269474: 3698, 0.39216906: 1143, 0.39201057: 3770, 0.3919557: 1537, 0.3919394: 1215, 0.39190477: 2437, 0.39180604: 208, 0.39129913: 1372, 0.39115813: 1361, 0.39107078: 1660, 0.3910305: 3716, 0.39101118: 1414, 0.39093933: 2442, 0.39057076: 1846, 0.39039785: 1438, 0.390268: 3623, 0.3901996: 191, 0.39017785: 3635, 0.3901763: 3700, 0.39010343: 3041, 0.38989604: 474, 0.3896598: 1189, 0.38957608: 1480, 0.38884053: 3854, 0.38878122: 1765, 0.3886481: 985, 0.3881033: 2742, 0.38787037: 1031, 0.38735747: 1274, 0.38731718: 2716, 0.3870455: 3402, 0.3869977: 1505, 0.38667393: 2139, 0.38667142: 2511, 0.3866174: 3225, 0.38654166: 125, 0.38635552: 1479, 0.38626787: 1541, 0.38624603: 3775, 0.38588747: 3410, 0.38588014: 3219, 0.38583776: 1080, 0.38575602: 1793, 0.38574395: 1144, 0.38545224: 3847, 0.38539785: 611, 0.3853553: 343, 0.38527203: 3132, 0.38513646: 118, 0.38507193: 3645, 0.38505098: 3681, 0.38488358: 3682, 0.3846789: 551, 0.38421953: 736, 0.384213: 2109, 0.3841486: 1730, 0.38403895: 3304, 0.3840073: 1163, 0.3838312: 418, 0.38379365: 2734, 0.38374704: 1271, 0.38372868: 1474, 0.3835192: 1783, 0.3829382: 614, 0.38272166: 1591, 0.38263786: 1145, 0.38245618: 3632, 0.3823522: 2432, 0.38207105: 1758, 0.382065: 2678, 0.38206473: 1655, 0.38177752: 1785, 0.3817587: 2477, 0.38148287: 1494, 0.38122874: 1801, 0.38115332: 450, 0.38113302: 2663, 0.3810675: 590, 0.38093626: 424, 0.38088: 3546, 0.3806501: 377, 0.38054115: 3135, 0.38052133: 2325, 0.38039723: 1169, 0.38018456: 64, 0.38017482: 1677, 0.38007057: 159, 0.3800432: 402, 0.37946635: 2269, 0.37837204: 2077, 0.37828493: 1648, 0.3782076: 871, 0.37817374: 3860, 0.37816513: 435, 0.37801513: 638, 0.37791336: 1070, 0.37789208: 3982, 0.3776025: 2532, 0.377457: 1181, 0.37722898: 375, 0.3772133: 1878, 0.37718463: 3472, 0.3770961: 264, 0.3769963: 3848, 0.37699175: 1214, 0.37666103: 572, 0.3765446: 3500, 0.37626013: 524, 0.3761924: 952, 0.3761575: 2931, 0.37605882: 1448, 0.37604475: 2075, 0.37603414: 1099, 0.37589464: 1453, 0.3758266: 1150, 0.37566745: 2495, 0.37561563: 1723, 0.37556773: 2213, 0.37555254: 2694, 0.37552997: 2719, 0.3750018: 811, 0.37493417: 2414, 0.37485442: 3254, 0.37469697: 1585, 0.37456244: 1238, 0.37452412: 548, 0.37452322: 2441, 0.37448096: 3285, 0.37427694: 3089, 0.3741482: 2786, 0.37384453: 425, 0.3737656: 2447, 0.37373382: 1687, 0.37372303: 1284, 0.373503: 535, 0.37350008: 4004, 0.37345815: 1594, 0.3733591: 2105, 0.37326866: 3141, 0.3732529: 3438, 0.37317228: 1739, 0.3731557: 891, 0.37312695: 1407, 0.37290108: 3618, 0.37256047: 473, 0.3725067: 128, 0.372473: 847, 0.37226236: 896, 0.3720856: 2616, 0.37200636: 2655, 0.37190354: 3983, 0.3715555: 2424, 0.37154955: 1371, 0.3715161: 1028, 0.3706448: 3232, 0.37034744: 3826, 0.37031317: 827, 0.37014002: 1768, 0.36989975: 2200, 0.36979365: 1900, 0.36956808: 342, 0.36949736: 2936, 0.3693178: 2375, 0.36928442: 3940, 0.36911622: 1590, 0.36906478: 306, 0.36904305: 2431, 0.369036: 1098, 0.3688709: 384, 0.3686096: 427, 0.3684331: 1221, 0.36839867: 2084, 0.36819166: 2722, 0.36817884: 2399, 0.36773983: 2412, 0.36749473: 1712, 0.36739838: 1513, 0.36732304: 1257, 0.36724657: 1695, 0.36711913: 2601, 0.36692923: 1002, 0.36689985: 2516, 0.36673656: 1129, 0.36670545: 2342, 0.36646852: 2141, 0.36646152: 2575, 0.36637047: 1777, 0.36633095: 2428, 0.36622798: 1763, 0.3660037: 3958, 0.36597562: 28, 0.36562824: 3822, 0.36560807: 1779, 0.36533397: 513, 0.36510748: 3713, 0.36482447: 475, 0.3647859: 3336, 0.36442423: 1122, 0.3644033: 67, 0.36433262: 1586, 0.3643265: 1991, 0.36426997: 1186, 0.36418006: 30, 0.36411893: 497, 0.36386454: 601, 0.36374497: 1178, 0.3636613: 230, 0.363571: 3009, 0.36349007: 946, 0.3633883: 3441, 0.3632585: 1043, 0.3631405: 340, 0.3631356: 1365, 0.36299986: 2498, 0.36299717: 3239, 0.36263382: 323, 0.36257905: 920, 0.36249343: 1101, 0.36234748: 2622, 0.36232594: 1527, 0.36230832: 3054, 0.36228836: 1384, 0.36227772: 587, 0.36222926: 3204, 0.36207044: 404, 0.36195827: 141, 0.36191118: 3913, 0.3616467: 3667, 0.3614645: 2317, 0.36134762: 3079, 0.36122844: 337, 0.36084884: 2638, 0.36071736: 844, 0.36051208: 2676, 0.36043856: 3117, 0.36026186: 394, 0.3601666: 1188, 0.36005765: 518, 0.36001393: 1034, 0.35998213: 217, 0.35996753: 2503, 0.359661: 544, 0.35940376: 1716, 0.35909116: 1614, 0.3588985: 98, 0.35888237: 850, 0.35865927: 3873, 0.35863787: 1455, 0.35855108: 1322, 0.35838395: 1694, 0.35834086: 1360, 0.35822323: 494, 0.35821098: 3399, 0.35807008: 2644, 0.3580258: 3082, 0.35801515: 2218, 0.35798433: 1266, 0.357932: 1033, 0.35792086: 2274, 0.3577145: 588, 0.35770863: 1580, 0.35758978: 1446, 0.35754174: 1045, 0.3575319: 1688, 0.35751757: 3404, 0.35732853: 339, 0.3571559: 3251, 0.35714582: 3824, 0.35708264: 3917, 0.35675487: 3739, 0.35649496: 2173, 0.35649103: 898, 0.35643286: 1350, 0.3564296: 1681, 0.35641184: 1428, 0.3563173: 3489, 0.35624894: 2351, 0.35537064: 3985, 0.35504428: 1134, 0.3549274: 2840, 0.35449305: 955, 0.35432458: 2452, 0.35430488: 1283, 0.3542603: 120, 0.35418987: 1236, 0.35411856: 2119, 0.35407218: 189, 0.35382086: 3629, 0.3537564: 411, 0.35360467: 203, 0.3535803: 3664, 0.3535495: 1084, 0.35344827: 3088, 0.35322052: 603, 0.3532042: 2196, 0.352872: 1124, 0.35286278: 2181, 0.352404: 2817, 0.35229865: 2114, 0.3522866: 3830, 0.35221887: 202, 0.35221165: 3969, 0.35218358: 3206, 0.35195965: 541, 0.35173744: 531, 0.3515558: 1462, 0.3515378: 2199, 0.3514624: 3476, 0.3511073: 2113, 0.35104862: 1111, 0.35071

127.0.0.1 - - [15/May/2024 14:30:44] "POST / HTTP/1.1" 200 -

-----

INPUT PROMPT:

        Comment:

        But Keto diet is high in fat and is advertised for weight loss !!!. losse skin After rapid weight lose (keto). after keto diet <br>what should I do for not gain weight. is it ok to follow your bodyweight exercise routine with keto diet?. Keto diet is effective for dramatic weight loss.. so, it&#39;s good for obese and overweight ppl, but make sure that it&#39;s for a short term only (no more than 4 months). I have a question about Keto. <br>I am now at a perfect weight. I do not want to lose more weight. How can I manage that being on Keto. <br>Looking forward to hearing from you. Thank you. Ursula. Now I&#39;m on diet for weight loss so how much time will I require to go in ketosis. Based on these pictures, the sum total is 1500-1700 calories.  Ketogenic or not, you&#39;ll lose weight on this.. Fasting and keto works , in fact it’s more effective than exercising for weight loss I lost 14 lbs without any exercises. I dont want to lose weight since im underweight but i want to fast anyway and do keto by not losing weight how can i do ??? because everytime i do keto i lose too much weight 😢

        Generate a summary?

-----

MODEL GENERATION -
Keto diet is effective for dramatic weight loss for obese and overweight ppl but make sure that it&#39;s for a short term only (no more than 4 months) Fasting and keto works in fact it’s more effective than exercising for weight loss. Ketogenic or not ketogenic dieters will lose weight on this diet whether they fast or not.


127.0.0.1 - - [15/May/2024 14:31:39] "POST / HTTP/1.1" 200 -

-----

INPUT PROMPT:

        Comment:

        is it ok to follow your bodyweight exercise routine with keto diet?. Sir can u send me one month keto Diet plan I wana reduce my 15 kg weight loss. Just wondering after the keto out, I&#39;ve learnt that I&#39;d better do the 7 day plan to come back to my normal diet in this video. So can I eat whatever I want to eat and exercise to keep the weight after the 7 day plan that you suggested? Would that maintain my weight? I really can&#39;t follow keto diet forever.. I&#39;d rather eat something I want and exercise to keep my weight.. is that a bad idea? I am on keto diet and this is my 2nd week and it is going pretty good (lost 3.5kg) but I just found from other Youtuber (I should have found that youtuber earlier so this would not have happened), that if I once start keto, it should be my lifestyle otherwise not to try. I am confused whether to keep on doing keto or not... it is good to lose weight but somehow hard to do it forever.. Could someone reply my questions above please?. Keto diet is effective for dramatic weight loss.. so, it&#39;s good for obese and overweight ppl, but make sure that it&#39;s for a short term only (no more than 4 months). My only regret is not trying the Agoge diet sooner, very good results. Keto really ruined me for a couple of weeks before that.. Veere.....pure veg. Keto diet plan bna do..... @gurumannfitness <a href="http://www.youtube.com/results?search_query=%23askgurumann">#askgurumann</a>. My only regret is not trying the Agoge diet sooner, very great results. Keto really ruined me for a couple of weeks before that.. Keto works but honestly I felt disgusting from the start. Then I tried the Agoge diet plan and it also worked, but I didn&#39;t feel bad at all, so I am sticking with the Agoge diet.. I’ve been on Keto diet for 1 week. Feel great i was not overweight, but had blood sugar roller coaster and mood swings.. Not getting hunger every few hours. I used to bake sourdough breads and cinnamon rolls. I don’t miss it. I have lots of deer , antelope and pheasant from hunting. I add olive oil and cheese. I’m going to stay with it.. But Keto diet is high in fat and is advertised for weight loss !!!

        Generate a summary?

-----

MODEL GENERATION -
Keto diet effective for dramatic weight loss for obese and overweight ppl, but make sure that it&#39;s for a short term only (no more than 4 months) My only regret is not trying the Agoge diet sooner, very good results. Keto really ruined me for a couple of weeks before that.. Veere.....pure veg. K keto diet plan bna do..... @gurumannfitness.


127.0.0.1 - - [15/May/2024 14:32:24] "POST / HTTP/1.1" 200 -

-----

INPUT PROMPT:

        Comment:

        I tried KETO ,  83 TO 68. My only regret is not trying the Agoge diet sooner, very great results. Keto really ruined me for a couple of weeks before that.. My only regret is not trying the Agoge diet sooner, very good results. Keto really ruined me for a couple of weeks before that.. Tru dat. I tried McDonald&#39;s fries after about a year of keto and they tasted like 💩.. I’ve tried Keto in the past, sure it had its benefits, but was the worst thing possible to go through.. I just started doing keto/intermittent fasting 16/8 and in 12 days I lost 9.1 lbs I love the bulletproof proof coffee and it does hold you until lunch. I will continue with it until I reach my goal. Sir i started the keto diet...its my 10th day but i lost only 1 kg...my weight is 61 kg and my age is 24...plzxxxxxx help me....m soooo upset.... Went keto 1/1/2017 ... very few plants... fully carnivore (except for coffee and low carb beer) since 10/1/2019 .. don&#39;t eat plants, don&#39;t expect to ever eat them again. Almost all meat, some eggs and cheeses... no fiber... perfect digestion. Feel amazing at 60.. Thank you for this. Been on keto for 3 years pre-pandemic and has massively improved my health. However I’ve fallen badly off the wagon during this pandemic - eating my feelings and consuming so much starch and sugar!!!! :( Ihave been feeling so bad about myself and hopeless because I felt I’ve crossed the line I am finding hard to go back. This has inspired me to try again and wishing this time I’ll succeed. Any tips would be most appreciated! Thanks!. Every time I see someone talk about keto, they make it seem like it’s ALL meat and fat and it’s bad for you. I don’t think that’s true at all, at least not for me. I’ve been keto for 2 years now and I have a big salad almost every day. You have to get your veggies in. I eat a lot of kale, spinach and lettuce. Eating fresh meat and vegetables is great for your body. I lost 60 lbs, went from eating a McDonald’s burger and fries to eating fresh meat and vegetables. Pretty sure that’s a no brainer.

        Generate a summary?

-----

MODEL GENERATION -
After a year of keto the fries tasted like a different kind of food. The Agoge diet led to a significant weight loss of 9.1 pounds in 12 days. Despite the negative effects of the keto diet the individual has maintained a healthy weight and improved their overall health. The individual has adopted a carnivore diet with no plants and no fiber.


127.0.0.1 - - [15/May/2024 14:33:21] "POST / HTTP/1.1" 200 -

-----

INPUT PROMPT:

        Comment:

        Sugar is a bad thing, talk to any type 2 diabetic who has overdosed, lost limbs through poor circulation, heart disease, blindness. Your book helped me get from diabetic to not diabetic, when the doctors tried to convince me of my body being incapable of producing insulin.. Tried it.  Never did anything for me.  Of course I don’t have diabetes do that’s probably why.. What do you do if your blood sugar goes up instead of down when you fast? I’ve struggled with this since becoming diabetic 6 years ago and my doctors can’t seem to tell me why this is.. I feel as a medical professional that if you have “ pre diabetes “ you have diabetes.. For comprehensive factual information on carbohydrates and the very real possibility of reversing type ll diabetes, check out the physician video presentations on &quot;Lowcarbdownunder&quot;.. THIS WAS ABSOLUTELY FANTASTIC!  I have metabolic syndrome, I am type-2 and I must be sugar addicted, never looked at it that way.  but it makes sense.  I love bread!  But all those repercussions due to the sugar is SPOT ON...  I got covid, gratefully I lived...  I lost about 25 lbs in 10 days of being ill..  by passed the cravings, as I was delirious...  and the weight fell off me...  trying hard to do the intermitted fasting, and guess now I will cut all carbs out....and I want to see for myself what 30 days without any carbs or low carbs will do for me.  I signed up for bariatric surgery.... because i have been having a heck of a time getting rid of this weight.  but I have to reverse this diabetes situation.  I&#39;m an American Indian and I have seen family and friends and other tribal people suffer greatly because of diabetes.  I have been one since 2017.  I had a life threatening car wreak in 2015 and was depressed and was unable to move etc....  hence the diabetes.  but I want out of it now..... Did she have diabetes or pre-diabetes? She is oversimplifying. Its not that easy. I tried gradual changes, but I only lowered blood sugar through a whole makeover in my lifestyle. It was a drastic change.. I am a 70 yrs old female, just recently informed by my doctor I am diabetic.  I have not started medication yet, nor has my doctor suggested  any yet.  Presently I am in denial of being diabetic, and giving myself until July 2024 to turn things around.  I really am puzzled how this happened, since I love my veggies, and fruits.  Yes there is times we eat crap food, and I do not consider myself extremely over weight. One question I do have is,  about 15 years ago, I had always complained about feeling so tired after eating any meals. A nap was always needed before I could do anything. When I questioned my doctor about this, he always shrugged his shoulders.  unable to answer me.  My question is, was this already the start of becoming diabetic?. I'm visiting my diabetic father. He eats very little and what he does eat is carbohydrates. He doesn't drink much water. Then he complains how awful he feels. I cooked him a steak a couple nights ago. That was all he ate, and about an hour later, he said he felt better than he had in days. Hmm...🤔 wonder why?

        Generate a summary?

-----

MODEL GENERATION -
An American Indian suffering from diabetes is in denial about her condition and giving herself until 2024 to reverse her condition. The author of the book "Sugar Addicted and Sugar Addicted" recommends cutting out carbohydrates in an effort to reverse diabetes. A person with pre-diabetes may have a better chance of reversing diabetes if they adopt a lowcarb diet and follow a healthy lifestyle.


127.0.0.1 - - [15/May/2024 14:34:20] "POST / HTTP/1.1" 200 -

-----

INPUT PROMPT:

        Comment:

        Help I am an insomniac<br>When I try to sleep my all truma or bad experiences won&#39;t let me sleep. I have suffered from insomnia for most of my life and it is so difficult to function. I’ve tried everything! 9 hours of sleep would be heavenly!. I have been battling insomnia for over 10 years. I tried everything that was ever suggested but sleeping pills were the only thing that worked until I discovered edible canibus which is legal in my state. I can fall asleep with it, but I wake up 2 1/2 hours later and struggle with getting back to sleep and that can happen more than once a night. In the past I tried every imaginable remedy like over the counter sleeping aids as well as natural ones like Melotonin, Valerian root, kava, tryptophan, sleep teas, Magnesium drinks etc.  I went to a hypnotherapist, an acupuncturist. I listened to sleep music/stories.  Did yoga and meditation and breathing exercises.  Nothing worked consistently.  Oh, and exercise too!  I may be tired, but I do not get sleepy on my own.  Being tired and being sleepy are different.  I must get enough sleep because I do not get tired during the day and my brain seems to function fine. Keto has helped me focus more and I have more energy, significantly lowered my blood sugar and belly fat and I have lost weight, but I still struggle with sleeping through the night.  Am I a lost cause?. I can’t sleep more than 7 but I feel like I need more , 🥺 so frustrating doc. Sleep would be nice; I rarely get a quality night of sleep without medicating myself into oblivion... and I&#39;ve tried all the &quot;tricks&quot;... I just don&#39;t sleep well. 😕. I HAVE TO HAVE 9 hours of sleep or I can&#39;t function! I thought there was something wrong with me!! Now that I&#39;m retired, I can do it! Feeling so much better!. I have a question- A lot of your information in this video concentrated on sleep.  I&#39;m a night person and have been since a teen.  I&#39;m now 64 and have severe insomnia and have for 20 years.  It&#39;s impossible for me to go to bed early.  Most nights I can&#39;t go to bed before 2:30 a.m. On the other nights it&#39;s not until between <a href="https://www.youtube.com/watch?v=Hq9cItue5tc&amp;t=180">3:00</a>/4:00 a.m.  Doesn&#39;t matter what I do or take for sleep...I just can&#39;t do it.  Since I started Ketovore 2 and a half weeks ago my insomnia has gotten worse with me being wide awake and I have to make myself lay down at <a href="https://www.youtube.com/watch?v=Hq9cItue5tc&amp;t=330">5:30</a>/6:00 a.m.  Why would this diet cause this?  It&#39;s not because the diet has given me energy either.  I&#39;ve lost 14 lbs so far and 2 inches off my waist but still have ZERO energy.. You would feel incredible. Sleep is good.. I tried a no sugar diet. It caused insurmountable anger, mood swings, and insomnia. At the end of 30 days, I started eating more sugar than I already had.. If you don&#39;t take care of your stress level and insomnia first, losing weight will be next to impossible because your body is releasing cortisol.

        Generate a summary?

-----

MODEL GENERATION -
A 64-year-old insomniac needs 9 hours of sleep to function properly. A ketogenic diet has improved energy and lowered blood sugar and belly fat but the individual still struggles to sleep through the night. A stress-related stress and insomnia can interfere with weight loss and weight loss leading to a lack of energy.


127.0.0.1 - - [15/May/2024 14:34:59] "POST / HTTP/1.1" 200 -

-----

INPUT PROMPT:

        Comment:

        When I stopped intermittent fasting, I gained a lot of weight. Amazing  lost 50 lbs,intermittent  fasting for 10 months,now on o.m.a.d.. thank  you DR.. Great info doc! Intermittent fasting offer several benefits like weight loss, improved metabolic health, and increased longevity. Thanks for sharing 🔥. Intermittent fasts is a norm in my life. If I fast for more then 36 hrs I feel sick and run down.
A higher metabolism makes the trip a short one.. I can exercise fasting no problem but after workout I feel super hungry. I was fasting with 2 meals a day and interval sprinting 2-3 times a week. I wasnt losing weight. I tried 1 meal a day. Dinner .and its working. I did intermittent fasting for 2 months...i lost around 12 kg..to then hit plateu..now i was wondering that if i stop fasting for a while..which for me its now been 3 months..so if I start fasting again i should start losing fat, but obviously at a slower rate....right?. So true on Fasting doing it since 1 month and results are awesome.. So when and how did intermittent fasting become eating less in a day vs just less often in a narrower window with longer periods in between!? Wouldn’t you still eat the same total amount of food throughout the entire day just in 2-3 larger meals vs 4-5 smaller ones? I certainly can’t see saving $500/month unless we’re talking about a big calorie deficit here where of course you’ll lose weight if that’s the case, but that’s a different topic altogether. Sorry doc, you lost some credibility with me here along with your wheatgrass sales pitch in another video - otherwise enjoy and appreciate most of the content.. Hi my age is 50 after 15 hours fasting last two months no weight loose

        Generate a summary?

-----

MODEL GENERATION -
Intermittent fasting offers weight loss, improved metabolic health, and increased longevity. Intermittent fasts is a norm in my life. If I fast for more than 36 hrs I feel sick and run down. I can exercise fasting no problem but after workout I feel super hungry. I tried 1 meal a day and its working.


127.0.0.1 - - [15/May/2024 14:35:36] "POST / HTTP/1.1" 200 -

-----

INPUT PROMPT:

        Comment:

        I started the Paleo diet over two years ago.  I lost 25 lbs that I needed to loose within the first two months with no effort.  I do not eat dairy because I am lactose intolerant, so that was no hardship for me.  Getting rid of grains and legumes in my diet made a huge difference.  I had suffered from a variety of stomach ailments and they disappeared when I started this diet.  It is easy to follow, but the only drawback for some people is you have to be willing to cook.  I use no packaged or processed foods, so food prep is a little more labor intensive, but I&#39;ve found really good ways to do this.  I usually have a couple of days a week that I cook up soups, stews and casseroles and freeze them for later use.  However, I like to cook so this is no hardship for me.  Most of all, I have lots of energy, sleep better and feel good on this Paleo lifestyle.  I do &quot;cheat&quot; now and then and eat a white potato rather than a sweet potato or have some dairy free ice cream, but I really don&#39;t do it often because I simply do not crave sweets at all.  I also never feel hungry with this diet and don&#39;t eat in between meals.  It works wonderfully for me!. Just got tired of being heavy and being in marginally poor health.  Finally decided to own it.  Went with a sort of Paleo diet but include some high fat dairy.  Meat, eggs, berries, avocados, peppers, cheese, whole milk, kraut.  Been 3 years and on cruise control.  Weight ⬇️ mental and physical energy ⬆️⬆️⬆️.. My diet is paleo, with about 70% meat protein.<br>Im very healthy,  lost a lot of fat and gain a lot of muscle.. I’ve been doing keto for a year and lost 30 pounds. The only reason why I would consider paleo is because I may be, well more than likely dairy intolerant. Great video, just subbed.. Years ago I was about 30lb overweight. I tried a low fat diet...put on more weight and felt terrible, always hungry. Switched to a strict Paleo diet - cutting out the majority of carbs. Lost all the weight in 3 months and didn't feel hungry between meals. Now I'm more Carnivore/Paleo and a good weight. I never have carbs with the evening meal. The main carbs I do eat are sweet potato - fries fab with a steak! or proper bakery sourdough bread with breakfast.. pork meat is best for kito diet i lost 5 kg in just a week thank you sir. I feel like I&#39;d do this for a time, then go on a traditional low-fat diet, etc... Dang I’m skinny and trying to go vegan but I don’t want to loose weight. Lost 48 lbs in about 1.5 years by cutting down sugar/sugary consumption and carbs, starches and red meat 😉<br><br>And I eat everything but in moderation but I can tell my body protests a lil bit 🤭😛. I lost 20 pounds with this diet

        Generate a summary?

-----

MODEL GENERATION -
Paleo diet has led to weight loss and improved energy and energy levels for those with intolerant dairy intolerant conditions such as lactose intolerant lactose intolerance. A keto diet led to a significant weight loss of 30 pounds over the course of a year. The Paleo diet has resulted in a significant improvement in physical and mental health as well as energy levels.

In [55]:
pred = "Your Question : " + query + "\nYour answer : " + output

In [56]:
print(pred)

Your Question : I want to adopt keto
Your answer : Ranveer credits Paaji's ketogenic diet for his successful weight loss journey. He credits his success to the support of Paaji and the Ahihek workoutzone. Paaji recommends the Agoge diet for weight loss but warns against the harmful effects of keto dieting. A nursing mother recommends Leviwiy Ketogenic Kaiserism as a potential alternative to keto for nursing mothers.