In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
!pip install fasttext

Collecting fasttext
  Downloading fasttext-0.9.2.tar.gz (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.8/68.8 kB 849.9 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pybind11>=2.2 (from fasttext)
  Using cached pybind11-2.11.1-py3-none-any.whl (227 kB)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from fasttext) (67.7.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from fasttext) (1.23.5)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (setup.py) ... done
  Created wheel for fasttext: filename=fasttext-0.9.2-cp310-cp310-linux_x86_64.whl size=4199771 sha256=bfb8793fc42d6ae9f1683eb1e62c9c59130b9e14917e28018a3a61c1f558c7d8
  Stored in directory: /root/.cache/pip/wheels/a5/13/75/f811c84a8ab36eedbaef977a6a58a98990e8e0f1967f98f394
Successfully built fasttext
Installing collected packages: pybind11, fasttext
Successfully installed fasttext-0.9.2 pybind11-2.11.1

In [ ]:
import pandas as pd
import numpy as np
import json
import fasttext
import re, os, shutil, json
from os import path
from numpy.linalg import norm
import pickle

# Stop Words Processing - for data cleaning
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
sw = set(stopwords.words('english'))
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
drive.mount('/content/gdrive')

defaultPath = "/content/gdrive/MyDrive/FYP1/"
Dataset_Folder = defaultPath + "Dataset/"
Processed_Dataset_Pickle_Path = Dataset_Folder + "processed_dataset.pkl"
Relevant_Comments_List_Pickle_Path = Dataset_Folder + "relevant_comments_list.pkl"
FastTextModelPath = defaultPath + "FastTextModelFile/cc.en.300-001.bin"

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

Reading Dataset Files and Merging them

In [ ]:
Dataset_Files = os.listdir(Dataset_Folder)

In [ ]:
DFs = []
length = 0

for file in Dataset_Files:
  if file.endswith('.csv'):
    df = pd.read_csv(Dataset_Folder + file, usecols=["author", "like_count", "text"])
    DFs.append(df)
    length = length + 1

In [ ]:
# Merging DataFrames

dataset_df = pd.concat(DFs)
dataset_df.shape

(1044, 3)

In [ ]:
dataset_df.head(5)

,author,like_count,text
0,Densi S,0,I have lost 12kgs in 3months
1,Anjaneyudu,0,Hi Channel admin &amp; all !!<br>I&#39;m serio...
2,Rishabh Yadav,2,10 kgs in 20 days Thanks to you didn&#39;t got...
3,Maryum R,0,Can anyone tell me that if I&#39;ll do keto di...
4,C B N,1,"If you wants to go for keto diet,first have to..."

Dataset Preprocessing

In [ ]:
# Defining Text Preprocing Function

def remove_stop_words(text):
  text_tokens = word_tokenize(text)
  tokens_without_sw = [word for word in text_tokens if not word in sw]
  return ' '.join(map(str, tokens_without_sw))


def preprocess(text):

    text = text.lower()
    text = text.replace("\\n", " ").replace("\n", " ")      # remove \n
    text = remove_stop_words(text)                          # remove stop words
    text = re.sub(r'\b\w{1,2}\b', ' ', text)                # remove words with 1 or 2 characters only
    text = re.sub(r'[^ a-zA-Z0-9]+','', text)                  # remove special characters / remove all except characters and spaces

    if text == "nan" or text == "none":
        text = " "
    text = re.sub(' +', ' ', text)

    return text.strip()

FastText - Features Generation

In [ ]:
fastText_model = fasttext.load_model(FastTextModelPath)

Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

In [ ]:
def fasttext_EmbeddingsGenerator(text):
  text_embeddings = fastText_model.get_word_vector(text)
  return text_embeddings #returns one feature vector.

Sentence Transformer - Features Generation

TF-IDF - Features Generation

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline

#print("no. of docs, no. of unique corpus words) : ", tfidf_features_array.shape)
#returns two dimensional feature array against the entire corpus(dataset).
def TFIDF_EmbeddingsGenerator(corpus):
  tfidf_model = TfidfVectorizer(stop_words='english')
  tfidf_model = tfidf_model.fit(corpus) #provide dataset.
  tfidf_features = tfidf_model.transform(corpus) #returns feature vectors.
  tfidf_features_array = tfidf_features.toarray() #converts to array.
  tfidf_features_list = []
  for arr in tfidf_features_array:
    tfidf_features_list.append(arr) #appending feature arrays into a list.
  return (tfidf_features_list, tfidf_model)

#generating feature array against the query.
#This function Takes in dataset's feature array and the query.
def TFIDF_QueryFeatureGeneration(tfidf_model, query):
  tfidf_features = tfidf_model.transform([query])
  tfidf_features_array = tfidf_features.toarray()
  return tfidf_features_array[0]

**Creating feature vectors of our Dataset**

In [ ]:
# Looping over dataset to generate feature vectors
processed_text = []
fasttext_features = []
tfidf_features = []

for index, row in dataset_df.iterrows():

  processed = preprocess(row["text"]) #sending data for cleaning.
  processed_text.append(processed) #appending in the list.

  # FastText Features Generator
  text_features = fasttext_EmbeddingsGenerator(processed) #takes in one comment at a time and returns features.
  fasttext_features.append(text_features)

  #Sentence Transformer Features Generator
  #
  #

# TFIDF Features Generator
(tfidf_features, tfidf_model) = TFIDF_EmbeddingsGenerator(processed_text) #passing the corpus. The func returns the trained model and extracted features.

dataset_df["processed_text"] = processed_text
dataset_df["fasttext_features"] = fasttext_features
dataset_df["tfidf_features"] = tfidf_features

dataset_df.to_pickle(Processed_Dataset_Pickle_Path, compression='infer', protocol=5, storage_options=None) #saving features data into pickle file.

**Reading Processed Dataset**

In [ ]:
dataset_df = pd.read_pickle(Processed_Dataset_Pickle_Path) #reading the file.
dataset_df.head(5)

,author,like_count,text,processed_text,fasttext_features,tfidf_features
0,Densi S,0,I have lost 12kgs in 3months,lost 12kgs 3months,"[-0.00079967454, 0.0032817647, -0.010505701, 0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,Anjaneyudu,0,Hi Channel admin &amp; all !!<br>I&#39;m serio...,channel admin amp seriously looking someones h...,"[0.00035663048, 0.00026676554, -0.005128587, 0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,Rishabh Yadav,2,10 kgs in 20 days Thanks to you didn&#39;t got...,kgs days thanks got overweight air force medic...,"[-0.0036859573, -0.0075673764, 0.014021413, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,Maryum R,0,Can anyone tell me that if I&#39;ll do keto di...,anyone tell keto diet days follow days diet ga...,"[-0.003192219, -0.0044949376, -0.011215435, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,C B N,1,"If you wants to go for keto diet,first have to...",wants keto diet first calculate calaries per w...,"[-0.010290721, -0.0021225929, -0.006684994, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [ ]:
print("fasttext", type(dataset_df["fasttext_features"]))
print("tfidf   ", type(dataset_df["tfidf_features"]))

fasttext <class 'pandas.core.series.Series'>
tfidf    <class 'pandas.core.series.Series'>

**Defining function to extract relevant comments w.r.t query**

In [ ]:
def cosine_similarity(A, B):

  # compute cosine similarity to find the similarity between two vectors.Higher the value, higher the similarity.
  cosine = np.dot(A,B)/(norm(A)*norm(B))
  return cosine


def get_relevant_comments_indices(query, comments, top_relevant_comments):
  #finding out relevant comments by returning indexes.
#comments: list of feature vectors.
  cosine_similarities = {}
  index = 0

  for comment in comments:
    cosine = cosine_similarity(query, comment) #calculating cosine similarity between query and the feature vector in feature vector list.
    cosine_similarities[cosine] = index #making a dictionary - key-value pair, cosine is the key and index is value.
    index = index + 1

  # Sort by key
  sorted_cosine_similarities = dict(sorted(cosine_similarities.items(), reverse = True)) #returning a dict of sorted keys(highest cosine value).
  print(sorted_cosine_similarities)
  # create a list of of relevant comments indices
  relevant_indices = []
  for i in range(0, top_relevant_comments): #top_relevant_comments= count.
    key, value = list(sorted_cosine_similarities.items())[i] #accessing top values to get the index of the comment.
    relevant_indices.append(value)

  return relevant_indices

**Ask user query and find relevant comments**

In [ ]:
query = input()

# query text preprocessing
processed_query = preprocess(query)

# FastText Features Generator
query_FastText_features = fasttext_EmbeddingsGenerator(processed_query)
# TFIDF Features Generator
query_TFIDF_features = TFIDF_QueryFeatureGeneration(tfidf_model, processed_query)


indices = get_relevant_comments_indices(query_TFIDF_features, dataset_df["tfidf_features"].tolist(), 10) #giving feature vectors of query and the dataset.

print(type(query_TFIDF_features), type(dataset_df["tfidf_features"].tolist()))
print(type(query_TFIDF_features[0]), type(dataset_df["tfidf_features"].tolist()[0]))

# I want to adopt keto diet

I want to adopt keto diet
{0.27321206198185893: 33, 0.2192733274438061: 383, 0.20367982207500882: 1017, 0.19954871306342553: 13, 0.1941955560616456: 253, 0.19410480839433053: 12, 0.1861527462803094: 278, 0.1817621447204832: 884, 0.17958500500251673: 375, 0.16126979783738482: 102, 0.1595562029291585: 58, 0.15756444614822301: 323, 0.1553604945904558: 434, 0.15044884135976452: 211, 0.14267379135307193: 877, 0.1419273920318557: 3, 0.1402095314851371: 373, 0.13976436117117322: 9, 0.13704633125129123: 540, 0.13584685026742654: 56, 0.1355817402499555: 929, 0.1342397793080043: 782, 0.13160158629223642: 691, 0.12968635336269893: 52, 0.1296226322335674: 196, 0.12884139111316542: 758, 0.12699480218447254: 10, 0.12635282167215167: 32, 0.1263226313892047: 374, 0.12499999584725402: 880, 0.12422727971575662: 344, 0.12039887203743821: 706, 0.11721728137250036: 255, 0.11559971445252187: 27, 0.11445860347471726: 238, 0.11343064188261469: 832, 0.11274781653582971: 1027, 0.11263339241446707: 46, 0.11088714886873134: 791, 0.10889581595133946: 284, 0.10856530110051218: 372, 0.10781938688719793: 369, 0.10650789220434688: 179, 0.10646584877893261: 57, 0.10642884615130818: 191, 0.10596018377628373: 416, 0.1055429382397116: 149, 0.10459612898560428: 364, 0.10349956738984836: 973, 0.10292223015704619: 162, 0.10287548120902572: 432, 0.10196393679453399: 48, 0.10161054664313734: 333, 0.10018591182801594: 242, 0.09953055678097647: 394, 0.09836690882015019: 535, 0.09815356279176102: 34, 0.09773702730606008: 49, 0.09757257450111236: 430, 0.09748698482172118: 54, 0.09717676473235187: 47, 0.0962405072755588: 301, 0.09444418364886933: 398, 0.09441005499806598: 55, 0.09382259385843711: 478, 0.09359642884287615: 227, 0.09357318169393314: 361, 0.09325104412112481: 470, 0.09313225864964489: 446, 0.09222596718555295: 4, 0.09219976002866957: 232, 0.09211432640583167: 357, 0.09148040395441279: 285, 0.0913232800595638: 334, 0.09121026630681763: 965, 0.09091481004184457: 425, 0.08983454540464887: 146, 0.08977738125670587: 956, 0.0883735850247363: 320, 0.08810220415564529: 266, 0.08800465546894598: 176, 0.0879144286044029: 79, 0.0879011828894706: 305, 0.08770837533352427: 11, 0.0868667295949353: 39, 0.08624604014011805: 287, 0.08577768836750527: 442, 0.08547880066120517: 779, 0.08533195636867956: 115, 0.08351361714772414: 123, 0.08269815859437742: 381, 0.08241175675469638: 732, 0.08240712500829436: 567, 0.08217341992717618: 272, 0.08142378825239412: 393, 0.0804657939559018: 252, 0.08045991347248388: 264, 0.08018504196851481: 189, 0.08009215525190988: 265, 0.07995204401195917: 61, 0.07906959168129915: 129, 0.07904162637333526: 213, 0.07833203637818391: 164, 0.07815829689173814: 239, 0.077947026980174: 260, 0.07756032007340191: 402, 0.077373683428653: 436, 0.07685399646763598: 51, 0.07684587572383313: 388, 0.07623644993827414: 350, 0.07577634322056478: 168, 0.0754199678359019: 304, 0.0744687250324686: 1014, 0.07417600751498994: 210, 0.07403377808261893: 359, 0.07382590514271027: 947, 0.0734713972137011: 660, 0.07346502541840334: 97, 0.07292984769538696: 493, 0.07277788420145595: 391, 0.07235901851112639: 365, 0.07107438446046009: 392, 0.07099390361185891: 315, 0.07080432967171024: 349, 0.0704260334320792: 101, 0.0703120624369233: 868, 0.06993420151029275: 178, 0.06966259395645304: 23, 0.06961182426621218: 268, 0.06822787988358608: 185, 0.06745218584397197: 118, 0.06737347351482302: 378, 0.06702722349891592: 987, 0.06687107199056222: 274, 0.06669857596421241: 652, 0.06643724798681847: 680, 0.06536582783121657: 325, 0.06528756834955785: 848, 0.06456089121665763: 431, 0.0644158793434463: 1031, 0.06440078636558222: 261, 0.06413599363797955: 348, 0.0637984615295207: 417, 0.06313991533648763: 7, 0.06308199904262038: 306, 0.06299831587652982: 82, 0.06299684380731793: 354, 0.0629617365350946: 309, 0.06288748358489175: 626, 0.06273145788528788: 797, 0.06198371675706442: 197, 0.061260103686853126: 105, 0.0602012787125803: 738, 0.06011507914219304: 925, 0.05967980686580285: 151, 0.059570888328106336: 410, 0.05955339200226202: 605, 0.059463952685872914: 328, 0.05938296056937123: 449, 0.058983227742005165: 110, 0.058390157699178366: 846, 0.05832497911964155: 939, 0.05824046338454323: 94, 0.05815945696294397: 335, 0.05770824870528136: 50, 0.05709763439823543: 817, 0.05693869606795683: 91, 0.05690459207343508: 330, 0.056699047534070325: 415, 0.05661043725124224: 198, 0.05640716976078627: 831, 0.05628621337061845: 1000, 0.05525831353013792: 414, 0.054963005873517594: 566, 0.054617889128734984: 474, 0.05432577209422907: 601, 0.054146940674094514: 296, 0.053990354650405074: 541, 0.0538702627403243: 36, 0.05384056593839521: 395, 0.05348215020146314: 578, 0.05294664792185633: 360, 0.05255718045176819: 574, 0.05243246699073744: 233, 0.05234856272553433: 571, 0.0519785689285409: 355, 0.05196450107533086: 222, 0.05163557368269957: 593, 0.051225990035611416: 486, 0.05090802763737699: 44, 0.05087606574333251: 45, 0.05026472699607773: 367, 0.04978957524679601: 53, 0.04926784115731178: 646, 0.04908482583572321: 288, 0.049004242736598036: 399, 0.0485613804766926: 518, 0.048549683166549173: 104, 0.048524425912489004: 251, 0.048295363371641364: 339, 0.04778537667261626: 875, 0.04768051178232565: 279, 0.04765930188561135: 994, 0.047572260009766054: 639, 0.04751490700309244: 619, 0.04689803694966216: 112, 0.04686128206562395: 319, 0.04637283165406179: 331, 0.04614351609887639: 181, 0.04589034369765377: 159, 0.04566358675631641: 92, 0.04564679920455214: 203, 0.045547422733409566: 550, 0.04547879060843318: 419, 0.045302687513882535: 25, 0.0449998079363465: 292, 0.04459718067403594: 85, 0.04441660745143006: 379, 0.04430121399761449: 280, 0.044106710731778166: 152, 0.04409973469762223: 790, 0.043996344194622596: 749, 0.043984525586452: 250, 0.04395290623436556: 786, 0.04389135231316252: 342, 0.043760394895328084: 75, 0.043669623456118266: 750, 0.04366431027646908: 229, 0.043599316813068424: 724, 0.04270170318206118: 73, 0.04266353296146132: 259, 0.042624479452003525: 270, 0.04257485530496697: 310, 0.04254857348392432: 86, 0.042542772821934485: 166, 0.042480468501905295: 293, 0.04247420825112119: 757, 0.04229980940099178: 155, 0.04217813401425838: 346, 0.04196642712144351: 928, 0.0419608712633259: 572, 0.04188072744593815: 988, 0.04154649801374947: 276, 0.04154404412997614: 411, 0.04105942864434483: 677, 0.041018217843305456: 607, 0.04095822520057897: 998, 0.04095418346241069: 24, 0.04058763542662866: 1041, 0.04032329057984967: 244, 0.04021015097645296: 1, 0.04013037945675584: 167, 0.040110026148426584: 689, 0.04009574858803763: 15, 0.04000643620458301: 993, 0.039899304590415074: 40, 0.039860641457858004: 515, 0.03964093947828755: 1032, 0.03950856924657137: 207, 0.039217148408858774: 409, 0.03873956621800038: 240, 0.03861564205737668: 533, 0.03860350194027403: 905, 0.03858116958058803: 247, 0.03851554831990808: 838, 0.038426040172854094: 954, 0.03842212279569638: 439, 0.038399103869710335: 412, 0.03828572580702825: 67, 0.037840528986101324: 193, 0.03782920646380372: 182, 0.03716301437264004: 588, 0.03696959972165168: 68, 0.03695970933268918: 514, 0.03689921140058148: 413, 0.03682534175378754: 659, 0.03667986007590334: 828, 0.03664666913387367: 132, 0.036349923646426585: 223, 0.0360911404222486: 237, 0.03579367686812507: 400, 0.035751571164234955: 611, 0.03545480347365604: 217, 0.03543579519649353: 314, 0.03542015964536294: 494, 0.03534150208940924: 600, 0.03463861666653868: 1002, 0.03443038918679635: 225, 0.03440885852821902: 555, 0.03413720847943527: 736, 0.03408822988811678: 570, 0.033898601377260924: 437, 0.033856419722303945: 568, 0.03339795661685086: 459, 0.03338147083296073: 256, 0.033275399789207995: 78, 0.03278966280066426: 974, 0.03274852199127613: 674, 0.03264342397074558: 338, 0.0325957345599505: 481, 0.03248803661696818: 1043, 0.03229781177098347: 175, 0.03226919473360674: 888, 0.031971574652259784: 627, 0.03167325897599754: 656, 0.03163802961868285: 885, 0.031586769051916826: 602, 0.03145961527538476: 502, 0.03137761658263354: 444, 0.031231203882878956: 377, 0.030811195000548092: 41, 0.030782741506089874: 362, 0.030552400187746458: 530, 0.030406406679134794: 74, 0.029905009928382263: 111, 0.029816704885493175: 608, 0.029701765014271242: 103, 0.029611305263937317: 69, 0.029328029854670184: 384, 0.02921938481707183: 71, 0.029111926383569315: 698, 0.029102863778021792: 972, 0.029042638798744136: 318, 0.028964698187270446: 80, 0.02884552237998443: 787, 0.028634673038457223: 37, 0.028437434195033497: 30, 0.028294666507772088: 243, 0.02827414814949324: 316, 0.028256738479543717: 522, 0.028161734916688996: 358, 0.028136507643503565: 257, 0.02805907981394248: 64, 0.028033036772336692: 352, 0.027972188783389224: 996, 0.027963677146054716: 482, 0.027946272736912556: 754, 0.027892575772839177: 785, 0.027858041270883392: 958, 0.027838909834720756: 837, 0.027755275970482156: 492, 0.027653340040321606: 507, 0.02752475543845726: 741, 0.027390441635611315: 919, 0.02731827808789411: 984, 0.027272423165351268: 582, 0.0272289462610585: 655, 0.027161449859632328: 215, 0.027155495102436263: 590, 0.027053373785735583: 762, 0.027036550060385536: 638, 0.026926319933850775: 1038, 0.026871293367744454: 300, 0.02683712105972513: 1040, 0.02668092149496497: 718, 0.026439600082995684: 72, 0.02641711731103767: 249, 0.026108399426216913: 345, 0.025879996493135052: 766, 0.02580294090901178: 456, 0.025663930605261138: 684, 0.025591127951178: 6, 0.02554303184267675: 686, 0.025350076763802454: 609, 0.02531945142927647: 241, 0.02530855100015899: 902, 0.02524787201606709: 701, 0.025188571772826046: 343, 0.0251346468449663: 803, 0.02504250928623106: 200, 0.02500085323515641: 708, 0.024937149253757576: 403, 0.024616580700391667: 603, 0.02425584840289818: 645, 0.024224703614322572: 401, 0.023917173720641758: 580, 0.023809007982311257: 512, 0.02380431416609368: 917, 0.023735916753938508: 537, 0.023711008484082953: 1016, 0.02359362917864822: 755, 0.023308559634234675: 128, 0.02296244049001464: 246, 0.02278800932392294: 752, 0.022775817480099: 664, 0.022730274868361242: 317, 0.022690633915012935: 737, 0.022583609676201963: 599, 0.022581289106630986: 371, 0.022363489563989657: 711, 0.021950081628665546: 420, 0.021927266604923366: 856, 0.02190988050822148: 143, 0.02174083845846796: 614, 0.021603208115221994: 822, 0.021562520501484897: 510, 0.021534117147205187: 42, 0.021499424111934954: 35, 0.021477649645655787: 937, 0.02132561210493848: 592, 0.021213309612968214: 892, 0.021157374145141735: 768, 0.021152026822334483: 499, 0.021138223357934156: 236, 0.020915658860805764: 144, 0.020898012215206634: 903, 0.020872846589749534: 351, 0.02080277951925177: 83, 0.020596952348064867: 487, 0.02037180414176824: 615, 0.020265254087436985: 642, 0.020204689481377863: 133, 0.020038419247549857: 575, 0.019919603856505926: 810, 0.019862384884755873: 675, 0.019819964050242896: 508, 0.019715746419393217: 915, 0.01958536100371737: 866, 0.019440118613313104: 477, 0.019416068669872926: 113, 0.019364351069095773: 804, 0.019147905489029605: 740, 0.01886995154162247: 62, 0.01886600891319965: 98, 0.018821219433333976: 525, 0.018768247278628927: 483, 0.018734035731871282: 31, 0.018659883405628325: 676, 0.018638715556031516: 520, 0.018261471210623603: 385, 0.018161633824576227: 505, 0.018129790561568836: 312, 0.018090535136638025: 539, 0.018034464936910875: 321, 0.01799341556622749: 653, 0.017912379025363658: 466, 0.017899393852001344: 862, 0.017880489927015967: 209, 0.017831193628418403: 517, 0.01781656759285629: 667, 0.01768872684241625: 341, 0.017490714654653707: 201, 0.017251019362071615: 649, 0.01714913834129034: 180, 0.01713768463317824: 500, 0.017098103033234037: 983, 0.016977660291130445: 717, 0.016639257806266246: 658, 0.016587890946894987: 165, 0.016541768363898292: 121, 0.016441564187356747: 219, 0.016406008457933934: 690, 0.01633194838365694: 729, 0.016250940187625094: 531, 0.01618175604365225: 1021, 0.01616758090027572: 405, 0.016149341298764414: 687, 0.016066207158054922: 307, 0.016009400575094087: 985, 0.015995986207516782: 781, 0.015827479314926594: 980, 0.015790877579412967: 29, 0.015710380550199427: 820, 0.015529519738200284: 733, 0.015513922899749092: 617, 0.015387588982028156: 139, 0.015283360107802412: 748, 0.015272103419383268: 148, 0.015235245349033323: 668, 0.015122820254311463: 814, 0.014934925731677547: 282, 0.014875150047655964: 970, 0.014852561167518853: 22, 0.01482477845440588: 547, 0.014667605954873817: 450, 0.014510154697878296: 960, 0.014426303262439752: 999, 0.014368180064186383: 273, 0.01412401659009585: 214, 0.013912434504627556: 734, 0.013816452932859167: 8, 0.01352675165561475: 577, 0.013487784731101122: 688, 0.013470185019012452: 504, 0.013467804402813434: 897, 0.013366305483101403: 1006, 0.013283669547241235: 792, 0.0131992674703521: 552, 0.013158685296773484: 833, 0.013016937572265184: 765, 0.012987462038392551: 606, 0.012770221356868457: 562, 0.012704797952383565: 910, 0.012680199830114291: 648, 0.01264175182725089: 697, 0.012523024274597052: 216, 0.012385950176666856: 513, 0.012369848717408682: 948, 0.012346625420302671: 556, 0.012097889910574762: 694, 0.012081396745477393: 799, 0.011846556220318674: 829, 0.011761451488658294: 699, 0.011755258012887187: 569, 0.011642677545520492: 997, 0.011601711686520435: 1011, 0.011556315591874445: 382, 0.0115318236425543: 585, 0.011413902649238205: 941, 0.011296350800686434: 943, 0.011243274588528222: 735, 0.01120330039075274: 663, 0.01113720346199111: 949, 0.010836219290340406: 511, 0.010817335236215586: 469, 0.010727123468852542: 551, 0.010717047682479162: 693, 0.0107006185271356: 975, 0.010389647913013403: 212, 0.010372514008751424: 290, 0.010355678808122087: 979, 0.010350917957353125: 821, 0.010282535343755964: 767, 0.010281128128664045: 1037, 0.010179615799979077: 267, 0.010069318495013269: 722, 0.010058394017273126: 670, 0.00977248688414381: 904, 0.009540145561568748: 809, 0.009514029760331385: 584, 0.0094144253394789: 772, 0.009323715363940723: 548, 0.009309934413258522: 545, 0.009305918397249237: 1029, 0.008744766877785404: 671, 0.008501436354332927: 812, 0.00826290756989658: 976, 0.008032438366641277: 744, 0.007969325303509113: 618, 0.00784439542778871: 989, 0.0077054881062416335: 581, 0.007425653313919462: 524, 0.007152037438166417: 623, 0.006778639856802095: 498, 0.006752654569773722: 685, 0.0065167043069614145: 933, 0.006487342282819798: 946, 0.006403529406995491: 387, 0.005979958053655592: 692, 0.005965581210345798: 616, 0.00465781695715613: 472, 0.0031216426094449836: 528, 0.0012845827393406495: 529, 0.0: 1042}
<class 'numpy.ndarray'> <class 'list'>
<class 'numpy.float64'> <class 'numpy.ndarray'>

In [ ]:
indices

[33, 383, 1017, 13, 253, 12, 278, 884, 375, 102]

In [ ]:
relevancy_count = 1
relevant_comments_list = []
Comments_str = ""

print("Most Relevant Comments w.r.t Query\n")
for index in indices:
  comment = dataset_df.iloc[index]["text"]
  print(str(relevancy_count) + " relevant comment: " + comment)
  relevancy_count = relevancy_count + 1
  relevant_comments_list.append(comment)
  Comments_str = Comments_str + comment + ". "


with open(Relevant_Comments_List_Pickle_Path, 'wb') as f:
  pickle.dump(relevant_comments_list, f)

Most Relevant Comments w.r.t Query

1 relevant comment: But I don&#39;t want to lose weight
2 relevant comment: after keto diet <br>what should I do for not gain weight
3 relevant comment: What can I do to gain weight? I don’t want to eat garbage but I also want to gain weight
4 relevant comment: Just wondering after the keto out, I&#39;ve learnt that I&#39;d better do the 7 day plan to come back to my normal diet in this video. So can I eat whatever I want to eat and exercise to keep the weight after the 7 day plan that you suggested? Would that maintain my weight? I really can&#39;t follow keto diet forever.. I&#39;d rather eat something I want and exercise to keep my weight.. is that a bad idea? I am on keto diet and this is my 2nd week and it is going pretty good (lost 3.5kg) but I just found from other Youtuber (I should have found that youtuber earlier so this would not have happened), that if I once start keto, it should be my lifestyle otherwise not to try. I am confused whether to keep on doing keto or not... it is good to lose weight but somehow hard to do it forever.. Could someone reply my questions above please?
5 relevant comment: I tried KETO ,  83 TO 68
6 relevant comment: I want to start with keto diet and I&#39;m a girl and I weigh around 84 KGS please tell me after completing 40 days of keto how much weight I can loose? also let me know wether having boiled eggs with some masala can be eaten In keto diet?
7 relevant comment: Hello sir , I want to know can a nursing mother go for keto diet to reduce weight
8 relevant comment: What if i dont want too loose weight?
9 relevant comment: sir i am very confused plz help i am 5 &#39;3.5&quot; and weight is 60 i want to increase height and also want muscles
10 relevant comment: You don&#39;t want to lose weight, you want to lose fat. By following stupid diet plans, I was primarily losing muscle mass. Oh god, how dumb I was? You only need correct diet and some kind of training, and the best thing is that you can find both (and much more) on website called Agoge Diet

In [ ]:
print(relevant_comments_list)

['But I don&#39;t want to lose weight', 'after keto diet <br>what should I do for not gain weight', 'What can I do to gain weight? I don’t want to eat garbage but I also want to gain weight', 'Just wondering after the keto out, I&#39;ve learnt that I&#39;d better do the 7 day plan to come back to my normal diet in this video. So can I eat whatever I want to eat and exercise to keep the weight after the 7 day plan that you suggested? Would that maintain my weight? I really can&#39;t follow keto diet forever.. I&#39;d rather eat something I want and exercise to keep my weight.. is that a bad idea? I am on keto diet and this is my 2nd week and it is going pretty good (lost 3.5kg) but I just found from other Youtuber (I should have found that youtuber earlier so this would not have happened), that if I once start keto, it should be my lifestyle otherwise not to try. I am confused whether to keep on doing keto or not... it is good to lose weight but somehow hard to do it forever.. Could someone reply my questions above please?', 'I tried KETO ,  83 TO 68', 'I want to start with keto diet and I&#39;m a girl and I weigh around 84 KGS please tell me after completing 40 days of keto how much weight I can loose? also let me know wether having boiled eggs with some masala can be eaten In keto diet?', 'Hello sir , I want to know can a nursing mother go for keto diet to reduce weight', 'What if i dont want too loose weight?', 'sir i am very confused plz help i am 5 &#39;3.5&quot; and weight is 60 i want to increase height and also want muscles', 'You don&#39;t want to lose weight, you want to lose fat. By following stupid diet plans, I was primarily losing muscle mass. Oh god, how dumb I was? You only need correct diet and some kind of training, and the best thing is that you can find both (and much more) on website called Agoge Diet']

**Text Sumarization**

In [ ]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.1-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 1.0 MB/s eta 0:00:00
Collecting datasets>=2.0.0 (from evaluate)
  Downloading datasets-2.16.0-py3-none-any.whl (507 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.1/507.1 kB 6.0 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.23.5)
Collecting dill (from evaluate)
  Downloading dill-0.3.7-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 11.7 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.5.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.31.0)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from evaluate) (4.66.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate) (3.4.1)
Collecting multiprocess (from evaluate)
  Downloading multiprocess-0.70.15-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 9.3 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]>=2021.05.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2023.6.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.19.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from evaluate) (23.2)
Collecting responses<0.19 (from evaluate)
  Downloading responses-0.18.0-py3-none-any.whl (38 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.13.1)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (10.0.1)
Collecting pyarrow-hotfix (from datasets>=2.0.0->evaluate)
  Downloading pyarrow_hotfix-0.6-py3-none-any.whl (7.9 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (3.9.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2023.11.17)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2023.3.post1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.9.4)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.4.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->evaluate) (1.16.0)
Installing collected packages: pyarrow-hotfix, dill, responses, multiprocess, datasets, evaluate
Successfully installed datasets-2.16.0 dill-0.3.7 evaluate-0.4.1 multiprocess-0.70.15 pyarrow-hotfix-0.6 responses-0.18.0

In [ ]:
import nltk
import numpy as np
import pickle
from datasets import load_dataset
from transformers import T5Tokenizer, DataCollatorForSeq2Seq
from transformers import T5ForConditionalGeneration, Seq2SeqTrainingArguments, Seq2SeqTrainer

from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM
from transformers import AutoTokenizer
from transformers import GenerationConfig

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

defaultPath = "/content/gdrive/MyDrive/FYP1/"
Dataset_Folder = defaultPath + "Dataset/"
Processed_Dataset_Pickle_Path = Dataset_Folder + "processed_dataset.pkl"
Relevant_Comments_List_Pickle_Path = Dataset_Folder + "relevant_comments_list.pkl"
FastTextModelPath = defaultPath + "FastTextModelFile/cc.en.300-001.bin"

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

**Read relevant_comments_list**

In [ ]:
relevant_comments_list = []

with open(Relevant_Comments_List_Pickle_Path, 'rb') as f:
  relevant_comments_list = pickle.load(f)

#relevant_comments_str = relevant_comments_list[0]
relevant_comments_str = ". ".join(relevant_comments_list) #merging all comments into a single string.

In [ ]:
#model_name='facebook/bart-large-cnn'
#model_name = "./results/checkpoint-22500"
#model_name='google/flan-t5-base'
#model_name='SyedShaheer/my_awesome_billsum_model'
model_name = "SyedShaheer/my_awesome_billsum_model2"
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

config.json:   0%|          | 0.00/1.66k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/328 [00:00<?, ?B/s]

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

tokenizer_config.json:   0%|          | 0.00/344 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.11M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

In [ ]:
dialogue = relevant_comments_str

prompt = f"""
Comment:

{dialogue}

Generate a summary?
"""

#generation_config = GenerationConfig(max_new_tokens=10, do_sample=True, temperature=0.5)

inputs = tokenizer(prompt, return_tensors='pt')


output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        max_new_tokens=100,
        #generation_config=generation_config,
        )[0],
    skip_special_tokens=True
)

print("-----\n")
print(f'INPUT PROMPT:\n{prompt}')

print("-----\n")
print(f'MODEL GENERATION - \n{output}\n')

-----

INPUT PROMPT:

Comment:

But I don&#39;t want to lose weight. after keto diet <br>what should I do for not gain weight. What can I do to gain weight? I don’t want to eat garbage but I also want to gain weight. Just wondering after the keto out, I&#39;ve learnt that I&#39;d better do the 7 day plan to come back to my normal diet in this video. So can I eat whatever I want to eat and exercise to keep the weight after the 7 day plan that you suggested? Would that maintain my weight? I really can&#39;t follow keto diet forever.. I&#39;d rather eat something I want and exercise to keep my weight.. is that a bad idea? I am on keto diet and this is my 2nd week and it is going pretty good (lost 3.5kg) but I just found from other Youtuber (I should have found that youtuber earlier so this would not have happened), that if I once start keto, it should be my lifestyle otherwise not to try. I am confused whether to keep on doing keto or not... it is good to lose weight but somehow hard to do it forever.. Could someone reply my questions above please?. I tried KETO ,  83 TO 68. I want to start with keto diet and I&#39;m a girl and I weigh around 84 KGS please tell me after completing 40 days of keto how much weight I can loose? also let me know wether having boiled eggs with some masala can be eaten In keto diet?. Hello sir , I want to know can a nursing mother go for keto diet to reduce weight. What if i dont want too loose weight?. sir i am very confused plz help i am 5 &#39;3.5&quot; and weight is 60 i want to increase height and also want muscles. You don&#39;t want to lose weight, you want to lose fat. By following stupid diet plans, I was primarily losing muscle mass. Oh god, how dumb I was? You only need correct diet and some kind of training, and the best thing is that you can find both (and much more) on website called Agoge Diet

Generate a summary?

-----

MODEL GENERATION -
I am on keto diet and this is my 2nd week and it is going pretty good (lost 3.5kg) but I just found from other Youtuber (I should have found that youtuber earlier so this would not have happened), that if I once start keto, it should be my lifestyle otherwise not to try. I am confused whether to keep on doing keto or not... it is good to lose weight but somehow hard to do it forever. Could