In [3]:

%pip install \
    transformers==4.27.2 \
    datasets==2.11.0 \
    evaluate==0.4.0 \
    rouge_score==0.1.2 \
    loralib==0.1.1 \
    peft==0.3.0

Collecting transformers==4.27.2
  Using cached transformers-4.27.2-py3-none-any.whl (6.8 MB)
Collecting datasets==2.11.0
  Using cached datasets-2.11.0-py3-none-any.whl (468 kB)
Collecting evaluate==0.4.0
  Using cached evaluate-0.4.0-py3-none-any.whl (81 kB)
Collecting rouge_score==0.1.2
  Using cached rouge_score-0.1.2-py3-none-any.whl
Collecting loralib==0.1.1
  Using cached loralib-0.1.1-py3-none-any.whl (8.8 kB)
Collecting peft==0.3.0
  Using cached peft-0.3.0-py3-none-any.whl (56 kB)
Requirement already satisfied: filelock in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from transformers==4.27.2) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from transformers==4.27.2) (0.19.4)
Requirement already satisfied: numpy>=1.17 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from transformers==4.27.2) (1.26.2)
Requirement already satisfied: packaging>=20.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from transformers==4.27.2) (23.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from transformers==4.27.2) (6.0.1)
Collecting regex!=2019.12.17 (from transformers==4.27.2)
  Using cached regex-2023.10.3-cp39-cp39-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: requests in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from transformers==4.27.2) (2.31.0)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1 (from transformers==4.27.2)
  Using cached tokenizers-0.13.3-cp39-cp39-win_amd64.whl (3.5 MB)
Requirement already satisfied: tqdm>=4.27 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from transformers==4.27.2) (4.65.0)
Requirement already satisfied: pyarrow>=8.0.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from datasets==2.11.0) (14.0.1)
Collecting dill<0.3.7,>=0.3.0 (from datasets==2.11.0)
  Using cached dill-0.3.6-py3-none-any.whl (110 kB)
Requirement already satisfied: pandas in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from datasets==2.11.0) (2.1.4)
Requirement already satisfied: xxhash in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from datasets==2.11.0) (3.4.1)
Requirement already satisfied: multiprocess in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from datasets==2.11.0) (0.70.15)
Requirement already satisfied: fsspec>=2021.11.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from fsspec[http]>=2021.11.1->datasets==2.11.0) (2023.10.0)
Requirement already satisfied: aiohttp in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from datasets==2.11.0) (3.9.1)
Collecting responses<0.19 (from datasets==2.11.0)
  Using cached responses-0.18.0-py3-none-any.whl (38 kB)
Collecting absl-py (from rouge_score==0.1.2)
  Using cached absl_py-2.0.0-py3-none-any.whl.metadata (2.3 kB)
Collecting nltk (from rouge_score==0.1.2)
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Requirement already satisfied: six>=1.14.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from rouge_score==0.1.2) (1.16.0)
Requirement already satisfied: psutil in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from peft==0.3.0) (5.9.0)
Requirement already satisfied: torch>=1.13.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from peft==0.3.0) (2.1.1)
Collecting accelerate (from peft==0.3.0)
  Downloading accelerate-0.25.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets==2.11.0) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets==2.11.0) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets==2.11.0) (1.9.4)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets==2.11.0) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets==2.11.0) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from aiohttp->datasets==2.11.0) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from huggingface-hub<1.0,>=0.11.0->transformers==4.27.2) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests->transformers==4.27.2) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests->transformers==4.27.2) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests->transformers==4.27.2) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from requests->transformers==4.27.2) (2023.11.17)
Requirement already satisfied: sympy in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from torch>=1.13.0->peft==0.3.0) (1.12)
Requirement already satisfied: networkx in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from torch>=1.13.0->peft==0.3.0) (3.1)
Requirement already satisfied: jinja2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from torch>=1.13.0->peft==0.3.0) (3.1.2)
Requirement already satisfied: colorama in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from tqdm>=4.27->transformers==4.27.2) (0.4.6)
Collecting safetensors>=0.3.1 (from accelerate->peft==0.3.0)
  Downloading safetensors-0.4.1-cp39-none-win_amd64.whl.metadata (3.8 kB)
INFO: pip is looking at multiple versions of multiprocess to determine which version is compatible with other requirements. This could take a while.
Collecting multiprocess (from datasets==2.11.0)
  Using cached multiprocess-0.70.14-py39-none-any.whl (132 kB)
Requirement already satisfied: click in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from nltk->rouge_score==0.1.2) (8.1.7)
Requirement already satisfied: joblib in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from nltk->rouge_score==0.1.2) (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from pandas->datasets==2.11.0) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from pandas->datasets==2.11.0) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from pandas->datasets==2.11.0) (2023.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from jinja2->torch>=1.13.0->peft==0.3.0) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in c:\users\shahe\anaconda3\envs\torch\lib\site-packages (from sympy->torch>=1.13.0->peft==0.3.0) (1.3.0)
Using cached regex-2023.10.3-cp39-cp39-win_amd64.whl (269 kB)
Using cached absl_py-2.0.0-py3-none-any.whl (130 kB)
Downloading accelerate-0.25.0-py3-none-any.whl (265 kB)
   ---------------------------------------- 0.0/265.7 kB ? eta -:--:--
   --------- ------------------------------ 61.4/265.7 kB 1.1 MB/s eta 0:00:01
   --------------------------------- ------ 225.3/265.7 kB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 265.7/265.7 kB 2.3 MB/s eta 0:00:00
Downloading safetensors-0.4.1-cp39-none-win_amd64.whl (277 kB)
   ---------------------------------------- 0.0/277.8 kB ? eta -:--:--
   ---------------------------------------- 277.8/277.8 kB 5.7 MB/s eta 0:00:00
Installing collected packages: tokenizers, safetensors, regex, loralib, dill, absl-py, responses, nltk, multiprocess, transformers, rouge_score, accelerate, peft, datasets, evaluate
  Attempting uninstall: dill
    Found existing installation: dill 0.3.7
    Uninstalling dill-0.3.7:
      Successfully uninstalled dill-0.3.7
  Attempting uninstall: multiprocess
    Found existing installation: multiprocess 0.70.15
    Uninstalling multiprocess-0.70.15:
      Successfully uninstalled multiprocess-0.70.15
  Attempting uninstall: datasets
    Found existing installation: datasets 2.15.0
    Uninstalling datasets-2.15.0:
      Successfully uninstalled datasets-2.15.0
Successfully installed absl-py-2.0.0 accelerate-0.25.0 datasets-2.11.0 dill-0.3.6 evaluate-0.4.0 loralib-0.1.1 multiprocess-0.70.14 nltk-3.8.1 peft-0.3.0 regex-2023.10.3 responses-0.18.0 rouge_score-0.1.2 safetensors-0.4.1 tokenizers-0.13.3 transformers-4.27.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, GenerationConfig, TrainingArguments, Trainer
import torch
import time
import evaluate
import pandas as pd
import numpy as np
from datasets import Dataset

In [2]:
huggingface_dataset_name = "DATA/paleo_filtered3_s.csv"

df = pd.read_csv(huggingface_dataset_name)
huggingface_dataset = Dataset.from_pandas(df)

huggingface_dataset = huggingface_dataset.train_test_split(test_size=0.3)
huggingface_dataset

DatasetDict({
    train: Dataset({
        features: ['author', 'published_at', 'updated_at', 'like_count', 'text', 'video', 'summary'],
        num_rows: 6
    })
    test: Dataset({
        features: ['author', 'published_at', 'updated_at', 'like_count', 'text', 'video', 'summary'],
        num_rows: 3
    })
})

In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
torch.cuda.set_device(0)

In [5]:
#model_name='google/flan-t5-base'
model_name='facebook/bart-large-cnn'
original_model = AutoModelForSeq2SeqLM.from_pretrained(model_name, torch_dtype=torch.bfloat16)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Some weights of BartForConditionalGeneration were not initialized from the model checkpoint at facebook/bart-large-cnn and are newly initialized: ['model.shared.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [6]:
prefix = "summarize: "


def preprocess_function(examples):
    inputs = [prefix + doc for doc in examples["text"]]
    model_inputs = tokenizer(inputs, max_length=1024, truncation=True)

    labels = tokenizer(text_target=examples["summary"], max_length=128, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [7]:
tokenized_billsum = huggingface_dataset.map(preprocess_function, batched=True)

Map:   0%|          | 0/6 [00:00<?, ? examples/s]

Map:   0%|          | 0/3 [00:00<?, ? examples/s]

In [8]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model_name)

In [9]:
import evaluate

rouge = evaluate.load("rouge")

In [10]:
import numpy as np


def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)

    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in predictions]
    result["gen_len"] = np.mean(prediction_lens)

    return {k: round(v, 4) for k, v in result.items()}

In [11]:
from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

Some weights of BartForConditionalGeneration were not initialized from the model checkpoint at facebook/bart-large-cnn and are newly initialized: ['model.shared.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [12]:
training_args = Seq2SeqTrainingArguments(
    output_dir="my_awesome_billsum_model2",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    save_total_limit=2,
    num_train_epochs=2,
    predict_with_generate=True,
    fp16=True,
    push_to_hub=True,
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_billsum["train"],
    eval_dataset=tokenized_billsum["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\huggingface_hub\utils\_deprecation.py:127: FutureWarning: 'Repository' (from 'huggingface_hub.repository') is deprecated and will be removed from version '1.0'. Please prefer the http-based alternatives instead. Given its large adoption in legacy code, the complete removal is only planned on next major release.
For more details, please read https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http.
  warnings.warn(warning_message, FutureWarning)
C:\Users\shahe\FYP_MODEL\my_awesome_billsum_model2 is already a clone of https://huggingface.co/SyedShaheer/my_awesome_billsum_model2. Make sure you pull the latest changes with `repo.git_pull()`.
C:\Users\shahe\Anaconda3\envs\torch\lib\site-packages\transformers\optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
You're using a BartTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

TrainOutput(global_step=2, training_loss=2.8411009311676025, metrics={'train_runtime': 48.0481, 'train_samples_per_second': 0.25, 'train_steps_per_second': 0.042, 'total_flos': 5383900495872.0, 'train_loss': 2.8411009311676025, 'epoch': 2.0})

In [13]:
output_dir = f'./results_check3'

In [14]:
trainer.save_model(output_dir)

Upload file pytorch_model.bin:   0%|          | 1.00/1.51G [00:00<?, ?B/s]

Upload file training_args.bin:   0%|          | 1.00/4.05k [00:00<?, ?B/s]

To https://huggingface.co/SyedShaheer/my_awesome_billsum_model2
   f911a54..0776d74  main -> main

WARNING:huggingface_hub.repository:To https://huggingface.co/SyedShaheer/my_awesome_billsum_model2
   f911a54..0776d74  main -> main

To https://huggingface.co/SyedShaheer/my_awesome_billsum_model2
   0776d74..9161a3b  main -> main

WARNING:huggingface_hub.repository:To https://huggingface.co/SyedShaheer/my_awesome_billsum_model2
   0776d74..9161a3b  main -> main

In [8]:
tokenized_datasets = tokenized_datasets.remove_columns(['author', 'published_at', 'updated_at', 'like_count', 'text', 'video', 'summary',])

In [9]:
print(tokenized_datasets)

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'labels'],
        num_rows: 6
    })
    test: Dataset({
        features: ['input_ids', 'labels'],
        num_rows: 3
    })
})

In [10]:
output_dir = f'./results_check'

In [11]:
import nltk
import evaluate
nltk.download("punkt", quiet=True)
metric = evaluate.load("rouge")

In [12]:
def compute_metrics(eval_preds):
   preds, labels = eval_preds

   # decode preds and labels
   labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
   decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
   decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

   # rougeLSum expects newline after each sentence
   decoded_preds = ["\n".join(nltk.sent_tokenize(pred.strip())) for pred in decoded_preds]
   decoded_labels = ["\n".join(nltk.sent_tokenize(label.strip())) for label in decoded_labels]

   result = metric.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
  
   return result

In [13]:
L_RATE = 1e-5
BATCH_SIZE = 2
PER_DEVICE_EVAL_BATCH = 2
WEIGHT_DECAY = 0.01
SAVE_TOTAL_LIM = 3
NUM_EPOCHS = 3

# Set up training arguments
training_args = TrainingArguments(
   output_dir="./results_check",
   learning_rate=L_RATE,
   per_device_train_batch_size=BATCH_SIZE,
   weight_decay=WEIGHT_DECAY,
   save_total_limit=SAVE_TOTAL_LIM,
   num_train_epochs=NUM_EPOCHS,
   gradient_accumulation_steps=4,
   fp16=True,
   push_to_hub=False
)

In [14]:
L_RATE = 1e-5
BATCH_SIZE = 1  # Adjusted to fit into 4GB GPU memory
PER_DEVICE_EVAL_BATCH = 2
WEIGHT_DECAY = 0.01
SAVE_TOTAL_LIM = 3
NUM_EPOCHS = 3

# Set up training arguments
training_args = TrainingArguments(
   output_dir="./results_check",
   learning_rate=L_RATE,
   per_device_train_batch_size=BATCH_SIZE,
   weight_decay=WEIGHT_DECAY,
   save_total_limit=SAVE_TOTAL_LIM,
   num_train_epochs=NUM_EPOCHS,
   gradient_accumulation_steps=2,  # Adjusted based on the smaller batch size
   fp16=False,  # Disable mixed precision training
   push_to_hub=False
)

In [21]:
metric = evaluate.load("accuracy")

Downloading builder script:   0%|          | 0.00/4.20k [00:00<?, ?B/s]

In [22]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [23]:
# Global Parameters
L_RATE = 1e-5
BATCH_SIZE = 2
PER_DEVICE_EVAL_BATCH = 2
WEIGHT_DECAY = 0.01
SAVE_TOTAL_LIM = 3
NUM_EPOCHS = 3

# Set up training arguments
training_args = TrainingArguments(
   output_dir="./results",
   evaluation_strategy="epoch",
   learning_rate=L_RATE,
   per_device_train_batch_size=BATCH_SIZE,
   per_device_eval_batch_size=PER_DEVICE_EVAL_BATCH,
   weight_decay=WEIGHT_DECAY,
   save_total_limit=SAVE_TOTAL_LIM,
   num_train_epochs=NUM_EPOCHS,
   push_to_hub=False
)

In [24]:
trainer = Trainer(
   model=original_model,
   args=training_args,
   train_dataset=tokenized_datasets["train"],
   eval_dataset=tokenized_datasets["test"],
   tokenizer=tokenizer,
   compute_metrics=compute_metrics
)

In [25]:
trainer.train()

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 3 dimensions. The detected shape was (2, 3, 512) + inhomogeneous part.

In [17]:
trainer.save_model(output_dir)

In [ ]:
last_checkpoint = "./results_check"

In [ ]:
original_model = AutoModelForSeq2SeqLM.from_pretrained(last_checkpoint, torch_dtype=torch.bfloat16)
tokenizer = AutoTokenizer.from_pretrained(last_checkpoint)

In [26]:
print(logits.shape)

NameError: name 'logits' is not defined